import {Black2World3D,esc} from '/frontend/world3d-runtime.js';
const $=s=>document.querySelector(s),R=window.Black2Runtime;
R.mountShell('world');
let rendererDiag={},lastScene=null,lastPlayer=null,lastActors=[],calTimer=null,calActive=false;
function rows(el,items){el.innerHTML=items.map(([k,v])=>`<div class="diag-row"><span>${esc(k)}</span><span>${esc(v??'—')}</span></div>`).join('')}
function pulse(id,state){const e=$(id);e.className='pulse '+(state==='good'?'good':state==='warn'?'warn':'')}
function entityList(el,items,render,empty='无数据'){el.innerHTML=items.length?items.map(render).join(''):`<div class="empty">${esc(empty)}</div>`}
function fmt(v,n=2){return Number.isFinite(Number(v))?Number(v).toFixed(n):'—'}

const viewer=new Black2World3D($('#world'),{
 onStatus(kind,state,detail){if(kind==='player')pulse('#playerPulse',state==='resolved'||state==='candidate'?'good':'warn');if(kind==='scene')pulse('#scenePulse',state==='resolved'||state==='candidate'?'good':'warn')},
 onProgress(done,total,label){$('#progressText').textContent=total?`${label} ${done}/${total}`:label},
 onScene(data){lastScene=data;renderScene(data);refreshLab(false)},
 onPlayer(p){lastPlayer=p;renderPlayer(p);if(calActive){}},
 onActors(a){lastActors=a;renderActors(a)},
 onActorMode(mode,meta){renderPlayerAsset(mode,meta)},
 onDiagnostics(d){rendererDiag=d;renderDiagnostics(d)},
 onFollowChange(v){$('#followToggle').checked=v;$('#followBtn').classList.toggle('primary',v)}
});

function renderScene(d){const s=d.static||{},m=s.matrix||{},a=s.area||{};$('#sceneKey').textContent=d.scene_key||'unresolved';$('#terrainCount').textContent=s.terrains?.length??0;$('#buildingCount').textContent=s.buildings?.length??0;$('#viewportBadge').innerHTML=`Zone ${esc(d.zone_id)} · ${esc(d.environment)}<br>Matrix ${esc(m.matrix_id)} · ${esc(m.width)}×${esc(m.height)}`;rows($('#sceneFacts'),[['Zone',d.zone_id],['Environment',d.environment],['Area',a.area_id],['Matrix',m.matrix_id],['Matrix size',m.width?`${m.width} × ${m.height}`:'—'],['Scene key',d.scene_key],['Identity',d.identity?.confidence],['Origin',d.scene_origin?`${fmt(d.scene_origin.x)}, ${fmt(d.scene_origin.z)}`:'—']])}
function renderPlayer(p){const g=p.grid||{},w=p.world||{},o=p.orientation||{},v=p.validation||{},l=p.locomotion||{};$('#playerState').textContent=p.status||'—';$('#frameText').textContent=`F ${p.frame??'—'}`;rows($('#playerFacts'),[['Zone',p.zone_id],['GPos',`${g.x??'—'}, ${g.y??'—'}, ${g.z??'—'}`],['WPos',`${fmt(w.x)}, ${fmt(w.y)}, ${fmt(w.z)}`],['Facing',`${o.facing??'—'} / ${o.facing_zh??'—'}`],['Motion',l.semantic_state],['Transport',l.transport_mode],['Chunk',p.chunk?`${p.chunk.x}, ${p.chunk.z}`:'—'],['Grid→World residual',`${fmt(v.residual_world?.x,3)}, ${fmt(v.residual_world?.z,3)}`],['Chunk check',v.chunk_matches_gpos],['Facing check',v.facing_crosscheck]])}
function renderPlayerAsset(mode,meta){rows($('#playerAsset'),[['Renderer',mode],['OBJCODE',meta?.obj_code],['Resource',meta?.resource_id],['Kind',meta?.resource_kind],['Magic',meta?.resource_magic]])}
function renderActors(actors){$('#npcCount').textContent=viewer.showActors?actors.length:'off';$('#actorRead').textContent=viewer.showActors?`${actors.length} actors`:'disabled';entityList($('#actorList'),actors,a=>`<div class="entity"><strong>slot ${esc(a.slot)} · UID ${esc(a.actor_uid)}</strong><div class="meta">model ${esc(a.model_id)} · ${esc(a.facing)}<br>GPos ${esc(a.grid?.x)},${esc(a.grid?.y)},${esc(a.grid?.z)}</div></div>`,'当前 Zone 没有非玩家 Runtime Actor');entityList($('#npcInspector'),actors,a=>`<div class="entity ${a.is_player?'good':''}"><strong>${a.is_player?'PLAYER':'NPC'} slot ${esc(a.slot)}</strong><div class="meta">actor_uid=${esc(a.actor_uid)} model_id=${esc(a.model_id)}<br>OBJCODE candidate=${esc(a.obj_code_candidate)}<br>WPos ${fmt(a.world?.x)}, ${fmt(a.world?.y)}, ${fmt(a.world?.z)}</div></div>`) }
function renderDiagnostics(d){$('#fpsText').textContent=`FPS ${d.fps??'—'}`;$('#buildingDiag').textContent=`${d.buildings_loaded??0}/${d.buildings_total??0}`;rows($('#perfFacts'),[['FPS',d.fps],['Scene load ms',d.scene_load_ms],['Terrain',`${d.terrain_loaded}/${d.terrain_total} · fail ${d.terrain_failed}`],['Buildings',`${d.buildings_loaded}/${d.buildings_total} · fail ${d.buildings_failed}`],['Player mode',d.player_mode],['NPC original',d.npc_original_count],['NPC fallback',d.npc_fallback_count]]);const failures=d.failed_assets||[];entityList($('#failedAssets'),failures,x=>`<div class="entity bad"><strong>${esc(x.kind)} · ${esc(x.id??'')}</strong><div class="meta">${esc(x.url)}<br>${esc(x.error)}</div></div>`,'没有资源加载失败');const bf=failures.filter(x=>x.kind==='building');entityList($('#buildingFailures'),bf,x=>`<div class="entity bad"><strong>Building ${esc(x.id)}</strong><div class="meta">${esc(x.url)}<br>${esc(x.error)}</div></div>`,'当前建筑资源全部加载成功')}

async function refreshLab(includeActors=false){try{const data=await R.jsonFetch(`/api/v1/lab/inspect?include_actors=${includeActors?'true':'false'}`,{},3500);const bs=data.nearby_buildings||[];$('#nearZone').textContent=`Zone ${data.scene?.zone_id??'—'}`;entityList($('#nearBuildings'),bs.slice(0,8),b=>`<div class="entity"><strong>UID ${esc(b.uid)} ${b.door_uid!=null?`· Door ${esc(b.door_uid)}`:''}</strong><div class="meta">XZ ${fmt(b.distance_xz_world,1)} · 3D ${fmt(b.distance_3d_world,1)}<br>${esc(b.id)}</div></div>`);entityList($('#buildingInspector'),bs.slice(0,15),b=>`<div class="entity"><strong>UID ${esc(b.uid)} ${b.has_door_metadata?`· Door ${esc(b.door_uid)}`:''}</strong><div class="meta">distance=${fmt(b.distance_xz_world,2)}<br>world=${fmt(b.world?.x)},${fmt(b.world?.y)},${fmt(b.world?.z)}</div></div>`);const n=data.navigation||{};$('#navNodes').textContent=n.node_count??0;rows($('#navFacts'),[['Nodes',n.node_count],['Directed edges',n.directed_edge_count],['Zones',(n.zones||[]).join(', ')],['Confidence',n.confidence]]);if(includeActors&&data.actors?.actors)renderActors(data.actors.actors)}catch(e){console.debug('lab inspect',e)}}
async function refreshSystem(){try{const h=await R.jsonFetch('/api/v1/runtime/health',{},1200);pulse('#httpPulse','good');pulse('#bridgePulse',h.bridge_connected?'good':'warn')}catch{pulse('#httpPulse','warn');pulse('#bridgePulse','warn')}}
async function refreshReports(){try{const d=await R.jsonFetch('/api/v1/lab/calibration/reports',{},2000);$('#reportList').innerHTML=(d.reports||[]).slice(0,8).map(r=>`<a class="report-link" href="${esc(r.download_url)}">${esc(r.name)} · ${esc(r.size_kb)} KB</a>`).join('')||'<div class="empty">暂无报告</div>'}catch{}}

$('#tabs').addEventListener('click',e=>{const b=e.target.closest('button[data-tab]');if(!b)return;document.querySelectorAll('#tabs button').forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('.tab-panel').forEach(p=>p.classList.toggle('active',p.dataset.panel===b.dataset.tab))});
$('#followBtn').onclick=()=>viewer.setFollow(!viewer.followPlayer);$('#followToggle').onchange=e=>viewer.setFollow(e.target.checked);$('#frameBtn').onclick=()=>viewer.framePlayer();$('#gridToggle').onchange=e=>viewer.setDebug(e.target.checked);$('#npcToggle').onchange=e=>{viewer.setRuntimeActors(e.target.checked);if(e.target.checked)refreshLab(true)};$('#refreshSceneBtn').onclick=()=>viewer.refreshScene(true);
$('#clearPathBtn').onclick=()=>{viewer.clearNavigationPath();$('#pathResult').textContent='路径已清除'};
$('#pathBtn').onclick=async()=>{const x=Number($('#goalX').value),z=Number($('#goalZ').value),yv=$('#goalY').value.trim();if(!Number.isFinite(x)||!Number.isFinite(z)){ $('#pathResult').textContent='请输入目标 X / Z';return}try{const r=await R.jsonFetch('/api/v1/lab/navigation/path',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({goal_x:x,goal_z:z,goal_y:yv===''?null:Number(yv),max_snap_radius:2})},3000);if(r.reachable){viewer.setNavigationPath(r.path);$('#pathResult').innerHTML=`<b>Observed 3D path</b><br>${esc(r.steps)} steps · ${esc(r.confidence)}<br>goal layer Y=${esc(r.goal?.y)}`}else{$('#pathResult').textContent=r.reason||'没有已验证路径'}}catch(e){$('#pathResult').textContent=e.message}};

async function calSample(){if(!calActive)return;try{const r=await R.jsonFetch('/api/v1/lab/calibration/sample',{method:'POST'},2500);$('#calStatus').textContent=`录制中 · ${r.sample_count} samples · 正常走动即可`}catch(e){$('#calStatus').textContent=`录制采样失败：${e.message}`}}
$('#calStart').onclick=async()=>{try{const r=await R.jsonFetch('/api/v1/lab/calibration/start',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({label:$('#calLabel').value,scenario:$('#scenario').value})},2000);calActive=true;$('#calStart').disabled=true;$('#calStop').disabled=false;$('#calStatus').classList.add('cal-active');$('#calStatus').textContent=`已开始 ${r.scenario}，请在游戏里按测试目的走动`;await calSample();calTimer=setInterval(calSample,350)}catch(e){$('#calStatus').textContent=e.message}};
$('#calStop').onclick=async()=>{if(calTimer)clearInterval(calTimer);calTimer=null;try{const r=await R.jsonFetch('/api/v1/lab/calibration/finish',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({renderer_diagnostics:viewer.diagnostics(),notes:'captured from World Lab v8'})},5000);calActive=false;$('#calStart').disabled=false;$('#calStop').disabled=true;$('#calStatus').classList.remove('cal-active');$('#calStatus').innerHTML=`报告已生成：<a href="${esc(r.download_url)}">${esc(r.zip_name)}</a><br>samples=${esc(r.summary?.sample_count)} · elevation changes=${esc(r.summary?.observed_elevation_changes)}`;refreshReports();refreshLab(false)}catch(e){$('#calStatus').textContent=e.message}};

viewer.start();refreshSystem();refreshLab(false);refreshReports();setInterval(refreshSystem,2000);setInterval(()=>refreshLab(viewer.showActors),2500);
