import {Black2World3D, esc as esc3d} from '/frontend/world3d-runtime.js';

const R=window.Black2Runtime,I=window.Black2I18n,$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const state={workspace:'world',dock:'events',runtime:null,bootstrap:null,viewer:null,scene:null,player:null,actors:[],dialogue:null,history:[],diag:null,selection:null,events:[],evidence:null,versions:null,calTimer:null,calActive:false,lastPlayer:null,clientEvents:[]};
const safe=(v,f='—')=>R.safe(v,f),pretty=v=>R.pretty(v),t=(k,f)=>I.t(k,f);

function confidence(value){const v=String(value||'unresolved').toLowerCase();return ['verified','probable','candidate','unresolved','error'].includes(v)?v:'candidate'}
function confBadge(value){const c=confidence(value);return `<span class="confidence-badge ${c}">${esc3d(t(`confidence.${c}`,c.toUpperCase()))}</span>`}
function fmt(v){if(v===null||v===undefined||v==='')return '—';if(typeof v==='number')return Number.isInteger(v)?String(v):v.toFixed(3);if(typeof v==='object')return JSON.stringify(v);return String(v)}
function factTable(rows){return `<div class="fact-table">${rows.map(([k,v])=>`<div class="fact-key">${esc3d(k)}</div><div class="fact-value">${esc3d(fmt(v))}</div>`).join('')}</div>`}
function docCard(title,body,meta=''){return `<section class="doc-card"><div class="doc-card-head"><span>${esc3d(title)}</span><span>${meta}</span></div><div class="doc-card-body">${body}</div></section>`}
function setMessage(msg){$('#statusMessage').textContent=msg}
function updateDot(id,status){const d=$(`[data-dot="${id}"]`),chip=$(`[data-health="${id}"]`);const c=status==='good'?'good':status==='bad'?'bad':'warn';if(d)d.className=`status-dot ${c}`;if(chip)chip.className=`health-chip ${c}`}

function sceneSelectionPayload(s){const st=s?.static||{};return {status:s?.status,confidence:s?.confidence,scene_key:s?.scene_key,zone_id:s?.zone_id,environment:s?.environment,coordinate_space:s?.coordinate_space,scene_origin:s?.scene_origin,identity:s?.identity,static_summary:{terrain_count:st.terrains?.length||0,building_count:st.buildings?.length||0,warp_count:st.entities?.warps?.length||0,trigger_count:st.entities?.triggers?.length||0,matrix:st.matrix,area:st.area,zone:st.zone}}}

function addClientEvent(kind,summary,confidenceValue='verified',details={}){state.clientEvents.unshift({source:'ui',kind,time:new Date().toISOString(),confidence:confidenceValue,summary,details});state.clientEvents=state.clientEvents.slice(0,120);if(state.dock==='events')renderDock()}

function workspaceFromHash(){const raw=location.hash.replace(/^#\/?/,'').split(/[/?]/)[0];return ['world','player','dialogue','memory','evidence','monitor','tools'].includes(raw)?raw:'world'}
function setWorkspace(id,push=true){if(state.workspace===id&&state.viewer)return;const old=state.workspace;state.workspace=id;if(push)history.replaceState(null,'',`#${id}`);$$('[data-workspace]').forEach(b=>b.classList.toggle('active',b.dataset.workspace===id));$$('.editor-pane').forEach(p=>p.classList.toggle('active',p.dataset.editor===id));$('#workspaceTitle').textContent=t(`workspace.${id}`,id);$('#editorTitle').textContent=id==='world'?'3D World':t(`workspace.${id}`,id);if(old==='world'&&id!=='world')destroyWorld();if(id==='world')ensureWorld();renderWorkspace();renderExplorer();}

function ensureWorld(){if(state.viewer)return;const host=$('#world');host.innerHTML='';state.viewer=new Black2World3D(host,{
  onStatus(kind,status,detail){if(kind==='player')updateDot('player',status==='resolved'||status==='candidate'?'good':'warn');if(kind==='scene'){updateDot('scene',status==='resolved'||status==='candidate'?'good':'warn');$('#worldOverlayDetail').textContent=detail||''}},
  onPlayer(p){const prev=state.player;state.player=p;$('#statusFrame').textContent=`F ${safe(p.frame)}`;$('#statusZone').textContent=`Zone ${safe(p.zone_id)}`;if(prev?.zone_id!=null&&p.zone_id!==prev.zone_id)addClientEvent('zone_transition',`Zone ${prev.zone_id} → ${p.zone_id}`,'verified',{from:prev.zone_id,to:p.zone_id,frame:p.frame});state.lastPlayer=prev;if(state.selection?.kind==='player')select({kind:'player',id:'player',payload:p},false)},
  onScene(s){state.scene=s;$('#worldOverlay').hidden=true;renderExplorer();if(!state.selection||state.selection.kind==='scene')select({kind:'scene',id:s.scene_key||'scene',payload:sceneSelectionPayload(s)},false);addClientEvent('scene_ready',s.scene_key||`Zone ${s.zone_id}`,s.confidence||'probable',{zone:s.zone_id})},
  onActors(a){state.actors=a;renderExplorer()},
  onDiagnostics(d){state.diag=d;$('#statusFps').textContent=`FPS ${safe(d.fps)}`;if(['assets','performance'].includes(state.dock))renderDock()},
  onSelect(sel){select(sel,true)},
  onProgress(done,total,label){setMessage(total?`${label} ${done}/${total}`:label)},
  onActorMode(mode,meta){addClientEvent('player_renderer',mode,mode?.includes('original')?'probable':'candidate',meta||{})}
});state.viewer.start();$('#worldOverlay').hidden=false;}
function destroyWorld(){if(!state.viewer)return;state.viewer.dispose();state.viewer=null;$('#world').innerHTML='';$('#worldOverlay').hidden=false;}

function renderWorkspace(){if(state.workspace==='player')renderPlayerEditor();else if(state.workspace==='dialogue')renderDialogueEditor();else if(state.workspace==='memory')renderMemoryEditor();else if(state.workspace==='evidence')loadEvidence();else if(state.workspace==='monitor')loadMonitor();else if(state.workspace==='tools')renderToolsEditor();}

function renderExplorer(){const body=$('#explorerBody'),filter=$('#explorerFilter').value.trim().toLowerCase();let html='';const match=x=>!filter||String(x).toLowerCase().includes(filter);
  if(state.workspace==='world'){
    const s=state.scene,st=s?.static||{},entities=st.entities||{};$('#explorerMeta').textContent=s?`Zone ${safe(s.zone_id)}`:'—';
    html+=treeSection(t('explorer.currentScene'),1,[treeRow('scene',s?.scene_key||'scene',s?`Zone ${safe(s.zone_id)} · ${safe(s.environment)}`:'unresolved','◎',sceneSelectionPayload(s))]);
    if(state.player&&match('player'))html+=treeSection(t('explorer.player'),1,[treeRow('player','player',`Player · ${safe(state.player.orientation?.facing)}`,'●',state.player)]);
    const terrain=(st.terrains||[]).filter(x=>match(`${x.id} ${x.chunk_id}`));html+=treeSection(t('explorer.terrain'),terrain.length,terrain.slice(0,160).map(x=>treeRow('terrain',x.id,`${x.id} · C${safe(x.chunk_id)}`,'◇',x)));
    const buildings=(st.buildings||[]).filter(x=>match(`${x.id} ${x.uid} ${x.door_uid}`));html+=treeSection(t('explorer.buildings'),buildings.length,buildings.slice(0,200).map(x=>treeRow('building',x.id||x.uid,`UID ${safe(x.uid)}${x.door_uid!=null?` · Door ${x.door_uid}`:''}`,'▣',x)));
    const actors=state.actors.filter(x=>match(`${x.slot} ${x.model_id} ${x.actor_uid}`));html+=treeSection(t('explorer.actors'),actors.length,actors.slice(0,120).map(x=>treeRow('npc',x.slot,`Slot ${x.slot} · Model ${safe(x.model_id)}`,'♟',x)));
    const warps=(entities.warps||[]).filter(x=>match(`${x.id} ${x.target_zone_or_map_raw}`));html+=treeSection(t('explorer.warps'),warps.length,warps.map(x=>treeRow('warp',x.id,`Warp ${x.id} → ${safe(x.target_zone_or_map_raw)}`,'↗',x)));
    const triggers=(entities.triggers||[]).filter(x=>match(x.id));html+=treeSection(t('explorer.triggers'),triggers.length,triggers.map(x=>treeRow('trigger',x.id,`Trigger ${x.id}`,'◆',x)));
  } else if(state.workspace==='player'){
    const p=state.player||state.bootstrap?.player||{};$('#explorerMeta').textContent=`F ${safe(p.frame)}`;html+=treeSection(t('player.cached'),1,[treeRow('player','player',`Player · ${safe(p.status)}`,'●',p)]);const a=p.addresses||p.root_chain||{};html+=treeSection(t('player.chain'),Object.keys(a).length,Object.entries(a).map(([k,v])=>treeRow('memory',k,`${k} · ${fmt(v)}`,'⌗',{name:k,value:v})));
  } else if(state.workspace==='dialogue'){
    const d=state.dialogue||{};$('#explorerMeta').textContent=d.active?'ACTIVE':'IDLE';html+=treeSection(t('dialogue.current'),1,[treeRow('dialogue','current',d.visible_text||t('dialogue.idle'),'▤',d)]);html+=treeSection(t('dialogue.history'),state.history.length,state.history.slice().reverse().slice(0,80).map((x,i)=>treeRow('dialogue_event',i,x.text||x.dialogue_text||x.current_text||`#${i}`,'·',x)));
  } else if(state.workspace==='evidence'){
    const reports=state.evidence?.reports?.reports||state.evidence?.reports||[];$('#explorerMeta').textContent=String(reports.length||0);html+=treeSection(t('evidence.reports'),reports.length||0,(reports||[]).map((x,i)=>treeRow('report',x.zip_name||i,x.label||x.zip_name||`Report ${i}`,'◆',x)));
  } else if(state.workspace==='monitor'){$('#explorerMeta').textContent=state.versions?.release||'—';html+=treeSection(t('monitor.versions'),state.versions?.components?.length||0,(state.versions?.components||[]).map(x=>treeRow('component',x.id,x.name,'⌁',x)));}
  else if(state.workspace==='tools'){$('#explorerMeta').textContent=String(state.bootstrap?.tools?.length||0);html+=treeSection(t('tools.title'),state.bootstrap?.tools?.length||0,(state.bootstrap?.tools||[]).map(x=>treeRow('tool',x.id,t(x.title_key,x.id),'⚙',x)));}
  else {$('#explorerMeta').textContent='';html=`<div class="empty-state">${esc3d(t('explorer.empty'))}</div>`}
  body.innerHTML=html||`<div class="empty-state">${esc3d(t('explorer.empty'))}</div>`;body.querySelectorAll('[data-select-kind]').forEach(el=>el.onclick=()=>{const payload=JSON.parse(decodeURIComponent(el.dataset.payload));select({kind:el.dataset.selectKind,id:el.dataset.selectId,payload},true)});
}
function treeSection(title,count,rows){return `<section class="tree-section"><div class="tree-head"><span>${esc3d(title)}</span><span class="tree-count">${count}</span></div>${rows.join('')||`<div class="empty-state">${esc3d(t('explorer.empty'))}</div>`}</section>`}
function treeRow(kind,id,label,icon,payload){const selected=state.selection?.kind===kind&&String(state.selection?.id)===String(id);return `<div class="tree-row ${selected?'selected':''}" data-select-kind="${esc3d(kind)}" data-select-id="${esc3d(id)}" data-payload="${encodeURIComponent(JSON.stringify(payload||{}))}"><span class="tree-icon">${icon}</span><span class="tree-label">${esc3d(label)}</span><span class="tree-note">${esc3d(kind)}</span></div>`}

function select(sel,user=true){if(!sel)return;state.selection={kind:sel.kind,id:sel.id,payload:sel.payload||{}};renderInspector();if(user){renderExplorer();if(state.dock==='memory')renderDock()}}
function selectionConfidence(sel){const p=sel?.payload||{};if(sel?.kind==='player')return p.confidence||(p.status==='resolved'?'probable':'unresolved');if(sel?.kind==='building')return p.resource?'probable':'candidate';if(sel?.kind==='npc')return p.confidence||'candidate';if(sel?.kind==='scene')return p.confidence||'probable';if(['warp','trigger','terrain'].includes(sel?.kind))return 'candidate';return p.confidence||'unresolved'}
function renderInspector(){const sel=state.selection,body=$('#inspectorBody'),badge=$('#selectionConfidence');if(!sel){body.innerHTML=`<div class="empty-state">${esc3d(t('inspector.nothing'))}</div>`;return}const c=confidence(selectionConfidence(sel));badge.className=`confidence-badge ${c}`;badge.textContent=t(`confidence.${c}`,c);const p=sel.payload||{};let rows=[];
  if(sel.kind==='player'){rows=[[t('common.status'),p.status],[t('common.frame'),p.frame],[t('common.zone'),p.zone_id],['GPos',p.grid?`${p.grid.x}, ${p.grid.y}, ${p.grid.z}`:'—'],['WPos',p.world?`${fmt(p.world.x)}, ${fmt(p.world.y)}, ${fmt(p.world.z)}`:'—'],['Facing',p.orientation?.facing],['Movement',p.locomotion?.semantic_state],['Transport',p.locomotion?.transport_mode],['Chunk',p.chunk?`${p.chunk.x}, ${p.chunk.z}`:'—']];}
  else if(sel.kind==='building'){rows=[['ID',p.id],[t('common.model'),p.uid],[t('common.door'),p.door_uid],[t('common.position'),p.world?`${fmt(p.world.x)}, ${fmt(p.world.y)}, ${fmt(p.world.z)}`:'—'],[t('common.rotation'),p.rotation_degrees],[t('common.source'),'ROM ChunkBuildings + AreaBuildingResource']];}
  else if(sel.kind==='npc'){rows=[['Slot',p.slot],['Actor UID',p.actor_uid],[t('common.model'),p.model_id],[t('common.zone'),p.zone_id],[t('common.position'),p.world?`${fmt(p.world.x)}, ${fmt(p.world.y)}, ${fmt(p.world.z)}`:'—'],['GPos',p.grid?`${p.grid.x}, ${p.grid.y}, ${p.grid.z}`:'—'],['Facing',p.facing],[t('common.source'),'RAM FieldActorSystem']];}
  else if(sel.kind==='scene'){rows=[[t('common.status'),p.status],[t('common.zone'),p.zone_id],['Environment',p.environment],['Scene Key',p.scene_key],['Coordinate Space',p.coordinate_space],['Identity',p.identity?.confidence]];}
  else if(sel.kind==='terrain'){rows=[['ID',p.id],['Chunk',p.chunk_id],[t('common.position'),p.world?`${fmt(p.world.x)}, ${fmt(p.world.y)}, ${fmt(p.world.z)}`:'—'],['Asset',p.asset_url],[t('common.source'),'ROM terrain']];}
  else if(sel.kind==='warp'){rows=[['ID',p.id],['Target Raw',p.target_zone_or_map_raw],['Target Warp',p.target_warp_id],['X',p.x_world],['Y',p.y_world],['Z',p.z],[t('common.source'),'ROM entity definition']];}
  else rows=Object.entries(p).slice(0,18).map(([k,v])=>[k,typeof v==='object'?JSON.stringify(v):v]);
  body.innerHTML=`<div class="inspector-section"><div class="inspector-heading"><span>${esc3d(sel.kind)} · ${esc3d(sel.id)}</span>${confBadge(c)}</div>${factTable(rows)}</div><div class="inspector-section"><div class="inspector-heading"><span>${esc3d(t('inspector.raw'))}</span></div><pre class="code-block">${esc3d(pretty(p))}</pre></div><div class="inspector-section"><div class="inspector-heading"><span>${esc3d(t('inspector.actions'))}</span></div><div class="inspector-actions"><button class="small-button" id="copySelection">${esc3d(t('inspector.copy'))}</button>${sel.kind==='player'?`<button class="small-button" id="frameSelection">${esc3d(t('world.frame'))}</button>`:''}</div></div>`;$('#copySelection').onclick=()=>navigator.clipboard?.writeText(pretty(p));const f=$('#frameSelection');if(f)f.onclick=()=>state.viewer?.framePlayer();
}

function renderPlayerEditor(){const p=state.player||state.bootstrap?.player||{};$('#playerEditor').innerHTML=`<div class="doc-head"><div><div class="doc-kicker">PLAYER RUNTIME</div><div class="doc-title">${esc3d(t('player.title'))}</div><div class="doc-desc">${esc3d(t('player.discoveryNote'))}</div></div><button class="tool" id="discoverPlayer">${esc3d(t('player.discovery'))}</button></div><div class="doc-grid">${docCard(t('player.position'),factTable([['GPos',p.grid?`${p.grid.x}, ${p.grid.y}, ${p.grid.z}`:'—'],['WPos',p.world?`${fmt(p.world.x)}, ${fmt(p.world.y)}, ${fmt(p.world.z)}`:'—'],[t('common.zone'),p.zone_id],[t('common.frame'),p.frame]]),confBadge(p.confidence))}${docCard(t('player.orientation'),factTable([['Facing',p.orientation?.facing],['FaceDir',p.orientation?.face_dir_raw],['Yaw',p.orientation?.yaw_degrees_if_model_forward_is_south],['Crosscheck',p.validation?.facing_crosscheck]]))}${docCard(t('player.movement'),factTable([['Phase',p.locomotion?.phase],['State',p.locomotion?.semantic_state],['Transport',p.locomotion?.transport_mode],['Gait',p.locomotion?.gait]]))}${docCard(t('player.mapper'),factTable([['Chunk',p.chunk?`${p.chunk.x}, ${p.chunk.z}`:'—'],['Tile size',p.chunk?.tile_size],['GPos↔Chunk',p.validation?.chunk_matches_gpos],['Grid residual X',p.validation?.residual_world?.x],['Grid residual Z',p.validation?.residual_world?.z]]))}</div><div class="doc-card" style="margin-top:10px"><div class="doc-card-head">${esc3d(t('inspector.raw'))}</div><div class="doc-card-body"><pre class="code-block">${esc3d(pretty(p))}</pre></div></div>`;$('#discoverPlayer').onclick=discoverPlayer;select({kind:'player',id:'player',payload:p},false)}
async function discoverPlayer(){setMessage(t('common.loading'));try{const p=await R.jsonFetch('/api/v1/player/runtime',{},8000);state.player=p;addClientEvent('player_discovery',p.status||'resolved',p.confidence||'probable',{frame:p.frame});renderPlayerEditor();renderExplorer()}catch(e){addClientEvent('player_discovery_error',String(e.message||e),'error');setMessage(String(e.message||e))}}

async function renderDialogueEditor(){const d=state.runtime?.snapshot?.dialogue||state.dialogue||{};state.dialogue=d;let history=state.history;try{const h=await R.jsonFetch('/api/dialogue/history?limit=60',{},1600);history=h.history||[];state.history=history}catch{}$('#dialogueEditor').innerHTML=`<div class="doc-head"><div><div class="doc-kicker">DIALOGUE</div><div class="doc-title">${esc3d(t('dialogue.title'))}</div></div><div><button class="tool" id="advanceDialogue">${esc3d(t('dialogue.advance'))}</button> <button class="tool" id="clearDialogue">${esc3d(t('dialogue.clear'))}</button></div></div><div class="doc-grid">${docCard(t('dialogue.current'),`<div class="callout ${d.active?'good':''}"><strong>${esc3d(d.speaker||d.speaker_category||'—')}</strong><div style="margin-top:6px;font-size:13px;color:var(--text)">${esc3d(d.visible_text||t('dialogue.idle'))}</div></div><div style="margin-top:8px"><div class="fact-key">${esc3d(t('dialogue.loaded'))}</div><pre class="code-block">${esc3d(d.loaded_text||'—')}</pre></div>`,confBadge(d.active?'probable':'unresolved'))}${docCard(t('dialogue.printer'),`<pre class="code-block">${esc3d(pretty(d.printer||{}))}</pre>`)}${docCard(t('dialogue.history'),history.slice().reverse().slice(0,30).map(x=>`<div class="link-card"><div><strong>${esc3d(x.speaker||x.speaker_category||'Dialogue')}</strong><span>${esc3d(x.text||x.dialogue_text||x.current_text||'')}</span></div><span class="tag">F ${esc3d(safe(x.frame))}</span></div>`).join('')||`<div class="empty-state">${esc3d(t('dock.empty'))}</div>`)}</div>`;$('#advanceDialogue').onclick=()=>R.jsonFetch('/api/actions/dialogue/advance?steps=1',{method:'POST'},5000);$('#clearDialogue').onclick=async()=>{await R.jsonFetch('/api/dialogue/clear',{method:'POST'});state.history=[];renderDialogueEditor()};renderExplorer()}

function renderMemoryEditor(){const selected=state.selection?.payload||{};const snap=state.runtime?.snapshot||{};$('#memoryEditor').innerHTML=`<div class="doc-head"><div><div class="doc-kicker">MEMORY</div><div class="doc-title">${esc3d(t('memory.title'))}</div><div class="doc-desc">${esc3d(t('memory.description'))}</div></div></div><div class="doc-grid">${docCard(t('memory.selection'),`<pre class="code-block">${esc3d(pretty(selected))}</pre>`,confBadge(state.selection?selectionConfidence(state.selection):'unresolved'))}${docCard(t('memory.rawSnapshot'),`<pre class="code-block">${esc3d(pretty(snap))}</pre>`)}${docCard(t('memory.tools'),`<a class="link-card" href="/frontend/memory-tracer.html"><div><strong>${esc3d(t('memory.openTracer'))}</strong><span>bounded trace / scan / snapshots</span></div><span>↗</span></a><a class="link-card" href="/dialogue-checkpoints"><div><strong>${esc3d(t('memory.openCheckpoints'))}</strong><span>frame-stamped dialogue evidence</span></div><span>↗</span></a><a class="link-card" href="/ram-dumper"><div><strong>${esc3d(t('memory.heavy'))}</strong><span>${esc3d(t('memory.heavyNote'))}</span></div><span>↗</span></a>`)}</div>`}

async function loadEvidence(){try{state.evidence=await R.jsonFetch('/api/v1/workbench/evidence',{},1800)}catch(e){state.evidence={error:String(e.message||e)}}renderEvidenceEditor();renderExplorer();if(state.dock==='calibration')renderDock()}
function reportRows(){const r=state.evidence?.reports?.reports||state.evidence?.reports||[];return Array.isArray(r)?r:[]}
function renderEvidenceEditor(){const reports=reportRows(),cal=state.evidence?.calibration||{},nav=state.evidence?.navigation||{};$('#evidenceEditor').innerHTML=`<div class="doc-head"><div><div class="doc-kicker">EVIDENCE</div><div class="doc-title">${esc3d(t('evidence.title'))}</div></div></div><div class="doc-grid">${docCard(t('evidence.calibration'),factTable([[t('common.status'),cal.status||cal.active],[t('common.count'),cal.sample_count],[t('evidence.scenario'),cal.scenario],[t('evidence.label'),cal.label]]))}${docCard(t('evidence.navigation'),factTable([['Nodes',nav.node_count],['Edges',nav.edge_count],['Zones',nav.zone_count],['Confidence',nav.confidence]]),confBadge(nav.confidence||'candidate'))}${docCard(t('evidence.reports'),reports.slice(0,20).map(x=>`<a class="link-card" href="/api/v1/lab/calibration/download/${encodeURIComponent(x.zip_name||'')}"><div><strong>${esc3d(x.label||x.zip_name||'report')}</strong><span>${esc3d(x.scenario||'')}</span></div><span>${esc3d(t('evidence.download'))} ↗</span></a>`).join('')||`<div class="empty-state">${esc3d(t('evidence.noReports'))}</div>`)}</div>`}

async function loadMonitor(){try{const [v,e]=await Promise.all([R.jsonFetch('/api/v1/workbench/versions'),R.jsonFetch('/api/v1/workbench/events?limit=80')]);state.versions=v;state.events=e.events||[]}catch(e){state.versions={error:String(e.message||e)}}renderMonitorEditor();renderExplorer();if(state.dock==='events')renderDock()}
function renderMonitorEditor(){const h=state.runtime?.health||{},v=state.versions||{};$('#monitorEditor').innerHTML=`<div class="doc-head"><div><div class="doc-kicker">RUNTIME</div><div class="doc-title">${esc3d(t('monitor.title'))}</div></div><button class="tool" id="monitorRefresh">${esc3d(t('monitor.refresh'))}</button></div><div class="doc-grid">${docCard(t('monitor.health'),factTable([[t('monitor.http'),state.runtime?.httpOnline?'online':'offline'],[t('monitor.bridge'),h.bridge_connected],[t('monitor.semantic'),h.semantic_status],[t('monitor.frame'),h.frame]]))}${docCard(t('monitor.versions'),(v.components||[]).map(x=>`<div class="link-card"><div><strong>${esc3d(x.name)}</strong><span>${esc3d(x.kind||'')}</span></div><span class="tag ${x.status==='compatible'?'good':'warn'}">${esc3d(x.observed_version||x.status)}</span></div>`).join('')||`<div class="empty-state">${esc3d(t('common.unavailable'))}</div>`)}${docCard(t('monitor.policy'),`<pre class="code-block">${esc3d(pretty(state.bootstrap?.performance_policy||{}))}</pre>`)}</div>`;$('#monitorRefresh').onclick=loadMonitor}

function renderToolsEditor(){const tools=state.bootstrap?.tools||[];$('#toolsEditor').innerHTML=`<div class="doc-head"><div><div class="doc-kicker">TOOLS</div><div class="doc-title">${esc3d(t('tools.title'))}</div><div class="doc-desc">${esc3d(t('tools.description'))}</div></div></div><div class="doc-grid">${tools.map(x=>docCard(t(x.title_key,x.id),`<div class="callout ${x.risk==='heavy-read'?'warn':''}">risk: ${esc3d(x.risk)}</div><div style="margin-top:8px"><a class="tool" href="${esc3d(x.href)}">${esc3d(t('action.openLegacy'))} ↗</a></div>`)).join('')}</div>`}

function renderDock(){const body=$('#dockBody');$$('[data-dock]').forEach(b=>b.classList.toggle('active',b.dataset.dock===state.dock));if(state.dock==='events'){const rows=[...state.clientEvents,...state.events].slice(0,120);body.innerHTML=`<table class="dock-table"><thead><tr><th>Time</th><th>Source</th><th>Event</th><th>${esc3d(t('inspector.confidence'))}</th><th>Summary</th></tr></thead><tbody>${rows.map(x=>`<tr><td>${esc3d((x.time||'').slice(11,23)||'—')}</td><td>${esc3d(x.source||'runtime')}</td><td>${esc3d(x.kind||'event')}</td><td>${confBadge(x.confidence)}</td><td>${esc3d(x.summary||'')}</td></tr>`).join('')||`<tr><td colspan="5">${esc3d(t('dock.empty'))}</td></tr>`}</tbody></table>`}
  else if(state.dock==='assets'){const f=state.diag?.failed_assets||[];body.innerHTML=`<table class="dock-table"><thead><tr><th>Kind</th><th>ID</th><th>URL</th><th>${esc3d(t('common.reason'))}</th></tr></thead><tbody>${f.map(x=>`<tr><td>${esc3d(x.kind)}</td><td>${esc3d(x.id||'—')}</td><td>${esc3d(x.url||'—')}</td><td>${esc3d(x.error||'—')}</td></tr>`).join('')||`<tr><td colspan="4">${esc3d(t('dock.empty'))}</td></tr>`}</tbody></table>`}
  else if(state.dock==='navigation'){const nav=state.bootstrap?.navigation||state.evidence?.navigation||{};body.innerHTML=`<div class="dock-form"><span>${esc3d(t('nav.observed'))}</span><input id="goalX" type="number" placeholder="${esc3d(t('nav.goalX'))}"><input id="goalY" type="number" placeholder="${esc3d(t('nav.goalY'))}"><input id="goalZ" type="number" placeholder="${esc3d(t('nav.goalZ'))}"><button class="tool" id="navPreview">${esc3d(t('nav.preview'))}</button><button class="tool" id="navClear">${esc3d(t('nav.clear'))}</button><span>nodes ${safe(nav.node_count,0)} · edges ${safe(nav.edge_count,0)}</span></div><div class="dock-note">${esc3d(t('nav.note'))}<span id="navResult"></span></div>`;$('#navPreview').onclick=previewPath;$('#navClear').onclick=()=>state.viewer?.clearNavigationPath()}
  else if(state.dock==='calibration'){const scenarios=['outdoor_flat','door_transition','indoor','stairs','bridge','npc','building','general'];body.innerHTML=`<div class="dock-form"><select id="calScenario">${scenarios.map(x=>`<option value="${x}">${esc3d(t(`cal.${x}`))}</option>`).join('')}</select><input id="calLabel" value="test" placeholder="${esc3d(t('evidence.label'))}"><button class="tool" id="calStart" ${state.calActive?'disabled':''}>${esc3d(t('evidence.start'))}</button><button class="tool" id="calStop" ${!state.calActive?'disabled':''}>${esc3d(t('evidence.stop'))}</button><span id="calState">${state.calActive?'REC':'IDLE'}</span></div>`;$('#calStart').onclick=startCalibration;$('#calStop').onclick=finishCalibration}
  else if(state.dock==='performance'){const d=state.diag||{},p=state.bootstrap?.performance_policy||{};body.innerHTML=`<div class="dock-form"><span>FPS ${safe(d.fps)}</span><span>Scene ${safe(d.scene_load_ms)} ms</span><span>Terrain ${safe(d.terrain_loaded,0)}/${safe(d.terrain_total,0)}</span><span>Buildings ${safe(d.buildings_loaded,0)}/${safe(d.buildings_total,0)}</span><span>NPC ${safe(d.npc_total,0)}</span><span>Failed ${safe(d.failed_assets?.length,0)}</span></div><pre class="code-block" style="margin:0 8px 8px">${esc3d(pretty(p))}</pre>`}
  else if(state.dock==='memory'){body.innerHTML=`<pre class="code-block" style="margin:8px">${esc3d(pretty(state.selection?.payload||state.runtime?.snapshot||{}))}</pre>`}
}

async function previewPath(){const x=Number($('#goalX').value),z=Number($('#goalZ').value),yv=$('#goalY').value,y=yv===''?null:Number(yv);if(!Number.isFinite(x)||!Number.isFinite(z))return;try{const r=await R.jsonFetch('/api/v1/lab/navigation/path',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({goal_x:x,goal_y:y,goal_z:z,max_snap_radius:2})},4000);$('#navResult').textContent=` · ${r.reachable?'reachable':'unresolved'} · ${r.path?.length||0} nodes`;if(r.reachable&&state.viewer)state.viewer.setNavigationPath(r.path||[]);addClientEvent('navigation_preview',`${x},${y??'*'},${z}`,r.confidence||'candidate',r)}catch(e){$('#navResult').textContent=` · ${e.message}`}}
async function startCalibration(){try{const scenario=$('#calScenario').value,label=$('#calLabel').value||'test';await R.jsonFetch('/api/v1/lab/calibration/start',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({scenario,label})},3000);state.calActive=true;state.calTimer=setInterval(()=>R.jsonFetch('/api/v1/lab/calibration/sample',{method:'POST'},2500).catch(()=>{}),450);addClientEvent('calibration_start',`${scenario}:${label}`,'verified');renderDock()}catch(e){addClientEvent('calibration_error',String(e.message||e),'error')}}
async function finishCalibration(){if(state.calTimer)clearInterval(state.calTimer);state.calTimer=null;try{const r=await R.jsonFetch('/api/v1/lab/calibration/finish',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({renderer_diagnostics:state.diag||{},notes:'Workbench v9'})},5000);state.calActive=false;addClientEvent('calibration_finish',r.zip_name||'report','verified',r);await loadEvidence();renderDock()}catch(e){state.calActive=false;addClientEvent('calibration_error',String(e.message||e),'error');renderDock()}}

function openPalette(){const pal=$('#palette');pal.hidden=false;$('#paletteInput').value='';renderPalette('');setTimeout(()=>$('#paletteInput').focus(),0)}function closePalette(){$('#palette').hidden=true}
const commands=[['world','workspace.world'],['player','workspace.player'],['dialogue','workspace.dialogue'],['memory','workspace.memory'],['evidence','workspace.evidence'],['monitor','workspace.monitor'],['tools','workspace.tools'],['discover','player.discovery'],['refresh','world.refresh']];
function renderPalette(q){const rows=commands.filter(([,k])=>`${t(k)} ${k}`.toLowerCase().includes(q.toLowerCase()));$('#paletteResults').innerHTML=rows.map(([id,k])=>`<div class="palette-result" data-command="${id}">${esc3d(t(k))}</div>`).join('');$$('[data-command]').forEach(x=>x.onclick=()=>{runCommand(x.dataset.command);closePalette()})}
function runCommand(id){if(['world','player','dialogue','memory','evidence','monitor','tools'].includes(id))setWorkspace(id);else if(id==='discover')discoverPlayer();else if(id==='refresh')state.viewer?.refreshScene(true)}

function bind(){I.apply();$('#localeSelect').value=I.getLocale();$('#localeSelect').onchange=e=>I.setLocale(e.target.value);I.subscribe(()=>{renderWorkspace();renderExplorer();renderInspector();renderDock();$('#workspaceTitle').textContent=t(`workspace.${state.workspace}`)});$$('[data-workspace]').forEach(b=>b.onclick=()=>setWorkspace(b.dataset.workspace));$('#explorerFilter').oninput=renderExplorer;$$('[data-dock]').forEach(b=>b.onclick=()=>{state.dock=b.dataset.dock;renderDock()});$('#dockCollapse').onclick=()=>$('#bottomDock').classList.toggle('collapsed');$('#commandButton').onclick=openPalette;$('#palette').onclick=e=>{if(e.target===$('#palette'))closePalette()};$('#paletteInput').oninput=e=>renderPalette(e.target.value);addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();openPalette()}if(e.key==='Escape')closePalette()});$('#followButton').onclick=()=>{if(!state.viewer)return;state.viewer.setFollow(!state.viewer.followPlayer);$('#followButton').classList.toggle('active',state.viewer.followPlayer)};$('#frameButton').onclick=()=>state.viewer?.framePlayer();$('#refreshSceneButton').onclick=()=>state.viewer?.refreshScene(true);$('#terrainToggle').onchange=e=>state.viewer?.setLayerVisibility('terrain',e.target.checked);$('#buildingToggle').onchange=e=>state.viewer?.setLayerVisibility('building',e.target.checked);$('#npcToggle').onchange=e=>state.viewer?.setRuntimeActors(e.target.checked);$('#gridToggle').onchange=e=>state.viewer?.setDebug(e.target.checked);addEventListener('hashchange',()=>setWorkspace(workspaceFromHash(),false));}

async function init(){bind();state.workspace=workspaceFromHash();try{state.bootstrap=await R.jsonFetch('/api/v1/workbench/bootstrap',{},2400);state.player=state.bootstrap.player||null;setMessage(`Workbench ${state.bootstrap.release}`)}catch(e){setMessage(`Bootstrap: ${e.message}`)}R.subscribe(model=>{state.runtime=model;const h=model.health||{};updateDot('http',model.httpOnline?'good':'bad');updateDot('bridge',h.bridge_connected?'good':'warn');const p=state.player||state.bootstrap?.player;updateDot('player',p&&p.status!=='unresolved'?'good':'warn');$('#statusFrame').textContent=`F ${safe(h.frame)}`;state.dialogue=model.snapshot?.dialogue||state.dialogue;if(state.workspace==='player'&&!state.viewer){state.player=state.player||state.bootstrap?.player;renderPlayerEditor()}if(state.workspace==='dialogue')renderDialogueEditor();});R.start(650);setInterval(async()=>{if(state.viewer||!['player','memory','evidence'].includes(state.workspace))return;try{const p=await R.jsonFetch('/api/v1/map/v6/player/live',{},1500);if(p&&p.status!=='unresolved'){state.player=p;if(state.workspace==='player')renderPlayerEditor();if(state.selection?.kind==='player')select({kind:'player',id:'player',payload:p},false)}}catch{}},500);try{const e=await R.jsonFetch('/api/v1/workbench/events?limit=80',{},1600);state.events=e.events||[]}catch{}setWorkspace(state.workspace,false);renderDock();}
init();
