import * as THREE from 'three';
import { GLTFLoader } from 'three/addons/loaders/GLTFLoader.js';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';

const API='/api/v1/map/v6';
const LAB='/api/v1/lab';
const TILE=16;
const PLAYER_POLL_MS=180;
const ACTOR_POLL_MS=1500;
const TARGET_RENDER_FPS=30;
const DIR_STEP=[0,3,2,3,0,1,3,0,0,0,4,0,4,2,2,2,3,3,3,3,3,3,0,0,0,0,0,3,3,3,3,3,2,2,0];
const sleep=ms=>new Promise(r=>setTimeout(r,ms));

async function getJSON(url,timeout=5000){const c=new AbortController(),t=setTimeout(()=>c.abort(),timeout);try{const r=await fetch(url,{cache:'no-store',signal:c.signal});if(!r.ok)throw new Error(`${r.status} ${await r.text()}`);return await r.json()}finally{clearTimeout(t)}}
function finite(v){return Number.isFinite(Number(v))?Number(v):null}
export function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}

export class Black2World3D{
  constructor(host,ui={}){
    this.host=host;this.ui=ui;this.disposed=false;
    this.scene=new THREE.Scene();this.scene.background=new THREE.Color(0x08111c);this.scene.fog=new THREE.FogExp2(0x08111c,.00055);
    this.camera=new THREE.PerspectiveCamera(42,1,.5,25000);
    this.renderer=new THREE.WebGLRenderer({antialias:false,alpha:false,powerPreference:'high-performance'});this.renderer.setPixelRatio(Math.min(devicePixelRatio||1,1.25));this.renderer.outputColorSpace=THREE.SRGBColorSpace;this.renderer.shadowMap.enabled=false;host.appendChild(this.renderer.domElement);
    this.controls=new OrbitControls(this.camera,this.renderer.domElement);this.controls.enableDamping=true;this.controls.dampingFactor=.08;this.controls.enablePan=true;this.controls.enableZoom=true;this.controls.screenSpacePanning=true;this.controls.minDistance=12;this.controls.maxDistance=12000;this.controls.mouseButtons.MIDDLE=THREE.MOUSE.PAN;this.controls.mouseButtons.RIGHT=THREE.MOUSE.PAN;this.controls.enabled=false;
    this.loader=new GLTFLoader();
    this.worldRoot=new THREE.Group();this.referenceRoot=new THREE.Group();this.staticRoot=new THREE.Group();this.actorRoot=new THREE.Group();this.pathRoot=new THREE.Group();this.debugRoot=new THREE.Group();this.worldRoot.add(this.referenceRoot,this.staticRoot,this.pathRoot,this.actorRoot,this.debugRoot);this.scene.add(this.worldRoot);
    this.scene.add(new THREE.HemisphereLight(0xe9f2ff,0x4a4438,2.1));const sun=new THREE.DirectionalLight(0xffffff,2.1);sun.position.set(-400,900,450);this.scene.add(sun);
    this.playerAnchor=new THREE.Group();this.playerAnchor.userData={kind:'player'};this.actorRoot.add(this.playerAnchor);this.playerVisual=null;this.playerVisualMode='none';this.gender=ui.gender||'male';this.playerMeta=null;this.billboardStep=0;this.lastBillboardFrame=null;this.spriteCache=new Map();
    this.player=null;this.sceneData=null;this.playerTarget=new THREE.Vector3();this.playerDisplay=new THREE.Vector3();this.origin=new THREE.Vector3();this.lastPlayerFrame=null;
    this.mountedSceneKey=null;this.loadingGeneration=0;this.sceneRequest=null;this.followPlayer=true;this.showActors=false;this.showDebug=false;this.navigationPath=[];this.actorMarkers=new Map();this.actorAssetCache=new Map();this.lastRenderAt=0;this.fpsFrames=0;this.fpsWindow=performance.now();this.fps=0;
    this.diag=this._newDiagnostics();this.selectionRoot=new THREE.Group();this.worldRoot.add(this.selectionRoot);this.raycaster=new THREE.Raycaster();this.pointer=new THREE.Vector2();this._onPick=e=>this._pick(e);this._onPointerMove=e=>this._hover(e);this.renderer.domElement.addEventListener('click',this._onPick);this.renderer.domElement.addEventListener('pointermove',this._onPointerMove);this._makeGrid();this.resize();addEventListener('resize',()=>this.resize());this._animate(performance.now());
  }
  _newDiagnostics(){return{scene_key:null,scene_load_ms:null,terrain_total:0,terrain_loaded:0,terrain_failed:0,terrain_fallback:0,buildings_total:0,buildings_loaded:0,buildings_failed:0,failed_assets:[],player_mode:this.playerVisualMode,npc_total:0,npc_original_count:0,npc_fallback_count:0,fps:this.fps}}
  diagnostics(){return{...this.diag,failed_assets:[...this.diag.failed_assets].slice(-100),fps:this.fps,player_mode:this.playerVisualMode,npc_total:this.actorMarkers.size}}
  _emitDiag(){this.ui.onDiagnostics?.(this.diagnostics())}
  resize(){const w=Math.max(1,this.host.clientWidth),h=Math.max(1,this.host.clientHeight);this.camera.aspect=w/h;this.camera.updateProjectionMatrix();this.renderer.setSize(w,h,false)}
  _makeGrid(){const g=new THREE.GridHelper(2048,128,0x435064,0x202833);g.position.y=.05;g.material.transparent=true;g.material.opacity=.28;g.visible=false;g.name='evidence-grid';this.debugRoot.add(g)}
  setDebug(v){this.showDebug=!!v;for(const o of this.debugRoot.children)o.visible=this.showDebug}
  setRuntimeActors(v){this.showActors=!!v;if(!v)this._clearActors();}
  setFollow(v){this.followPlayer=!!v;this.controls.enabled=!this.followPlayer;if(!v)this.controls.target.copy(this.playerDisplay);this.ui.onFollowChange?.(this.followPlayer)}
  framePlayer(){if(!this.player)return;this._frameCamera(this.sceneData?.environment)}
  async start(){this._discoverPlayer();this._playerLoop();this._actorLoop();this.ui.onStatus?.('scene','unresolved','waiting player')}
  async _discoverPlayer(){try{this.ui.onStatus?.('player','candidate','discovering runtime');const p=await getJSON('/api/v1/player/runtime',14000);this.applyPlayer(p);this.ui.onStatus?.('player',p.status||'unresolved',p.frame!=null?`f${p.frame}`:'discovery complete');return p}catch(e){this.ui.onStatus?.('player','degraded',`discovery: ${e.message}`);return null}}
  async _playerLoop(){while(!this.disposed){try{const p=await getJSON(`${API}/player/live`,2200);this.applyPlayer(p);this.ui.onStatus?.('player',p.status||'unresolved',`f${p.frame??'—'}`)}catch(e){this.ui.onStatus?.('player','degraded',e.message)}await sleep(PLAYER_POLL_MS)}}
  async _actorLoop(){while(!this.disposed){await sleep(ACTOR_POLL_MS);if(!this.showActors)continue;try{const r=await getJSON(`${LAB}/actors/live`,3000);await this.applyActors(r.actors||[])}catch(e){this.ui.onStatus?.('actors','degraded',e.message)}}}
  async refreshScene(force=false){if(this.sceneRequest)return this.sceneRequest;const req=this._refreshScene(force);this.sceneRequest=req;try{return await req}finally{if(this.sceneRequest===req)this.sceneRequest=null}}
  async _refreshScene(force){if(!this.player||this.player.status==='unresolved'){if(force)await this._discoverPlayer();if(!this.player||this.player.status==='unresolved')return false}const data=await getJSON(`${API}/scene/current`,5000);if(data.status==='unresolved')return false;const key=data.render_key||data.scene_key||`zone:${data.zone_id}`;if(force||key!==this.mountedSceneKey)await this._rebuildStaticAtomic(data,key);this.sceneData=data;this.ui.onScene?.(data);return true}
  _display(p,origin=this.origin){return new THREE.Vector3(finite(p?.x)??0,finite(p?.y)??0,finite(p?.z)??0).sub(origin)}
  _disposeRoot(root){const geometries=new Set(),materials=new Set(),textures=new Set();root?.traverse?.(o=>{if(o.geometry)geometries.add(o.geometry);const ms=o.material?(Array.isArray(o.material)?o.material:[o.material]):[];for(const m of ms.filter(Boolean)){materials.add(m);if(m.map)textures.add(m.map)}});for(const t of textures)t.dispose?.();for(const m of materials)m.dispose?.();for(const g of geometries)g.dispose?.();root?.clear?.()}
  async _rebuildStaticAtomic(data,key){const started=performance.now(),generation=++this.loadingGeneration,nextRoot=new THREE.Group(),nextOrigin=new THREE.Vector3(finite(data.scene_origin?.x)??0,0,finite(data.scene_origin?.z)??0);const st=data.static||{},terrain=st.terrains||[],buildings=st.buildings||[],cache=new Map();this.diag=this._newDiagnostics();this.diag.scene_key=key;this.diag.terrain_total=terrain.length;this.diag.buildings_total=buildings.length;this.ui.onProgress?.(0,terrain.length+buildings.length,'loading');let done=0;
    const load=async(url,kind,id)=>{if(cache.has(url))return cache.get(url);const p=new Promise((resolve,reject)=>this.loader.load(url,g=>{g.scene.traverse(o=>{if(o.isMesh){o.frustumCulled=true;const ms=Array.isArray(o.material)?o.material:[o.material];for(const m of ms.filter(Boolean)){m.side=THREE.DoubleSide;if(m.map){m.map.colorSpace=THREE.SRGBColorSpace;m.map.magFilter=THREE.NearestFilter;}m.needsUpdate=true}}});resolve(g.scene)},undefined,reject));cache.set(url,p);try{return await p}catch(e){this.diag.failed_assets.push({kind,id,url,error:String(e.message||e)});throw e}};
    const pool=async(items,n,fn)=>{let i=0;await Promise.all(Array.from({length:Math.min(n,items.length)},async()=>{while(i<items.length){const idx=i++;await fn(items[idx])}}))};
    await pool(terrain,3,async item=>{if(generation!==this.loadingGeneration)return;try{if(!item.asset_url){nextRoot.add(this._terrainCoordinateFallback(item,nextOrigin,data));this.diag.terrain_fallback++;return}const base=await load(item.asset_url,'terrain',item.id);if(generation!==this.loadingGeneration)return;const o=base.clone(true);o.position.copy(this._display(item.world,nextOrigin));o.name=item.id;o.userData={kind:'terrain',item};nextRoot.add(o);o.updateMatrixWorld(true);this.diag.terrain_loaded++}catch{this.diag.terrain_failed++;nextRoot.add(this._terrainCoordinateFallback(item,nextOrigin,data));this.diag.terrain_fallback++}finally{this.ui.onProgress?.(++done,terrain.length+buildings.length,'terrain')}});
    await pool(buildings,2,async item=>{if(generation!==this.loadingGeneration)return;try{const base=await load(item.asset_url,'building',item.id||item.uid);if(generation!==this.loadingGeneration)return;const o=base.clone(true);o.position.copy(this._display(item.world,nextOrigin));o.rotation.y=(finite(item.rotation_degrees)??0)*Math.PI/180;o.name=item.id||`building-${item.uid}`;o.userData={kind:'building',uid:item.uid,door_uid:item.door_uid,item};nextRoot.add(o);o.updateMatrixWorld(true);this.diag.buildings_loaded++}catch{this.diag.buildings_failed++}finally{this.ui.onProgress?.(++done,terrain.length+buildings.length,'building')}});
    if(generation!==this.loadingGeneration)return false;const old=this.staticRoot;this.worldRoot.remove(old);this.staticRoot=nextRoot;this.worldRoot.add(this.staticRoot);this._disposeRoot(old);this.origin.copy(nextOrigin);this.mountedSceneKey=key;this.sceneData=data;this.worldRoot.updateMatrixWorld(true);this._updateReferenceGrid(terrain,nextOrigin);this.diag.scene_load_ms=Math.round(performance.now()-started);this.scene.fog.density=data.environment==='interior'?.0012:.00052;if(this.player){const d=this._display(this.player.world);this.playerDisplay.copy(d);this.playerTarget.copy(d);this.playerAnchor.position.copy(d)}await this._ensurePlayerVisual();this._clearActors();this._frameCamera(data.environment);this.ui.onProgress?.(done,terrain.length+buildings.length,'ready');this._emitDiag();return true}
  _updateReferenceGrid(terrain,origin){this._disposeRoot(this.referenceRoot);const span=Math.max(TILE,finite(this.sceneData?.static?.chunk_span_world)??512),divisions=Math.max(1,Math.round(span/TILE));for(const item of terrain){const pos=this._display(item.world,origin);let y=(finite(item.world?.y)??0)-.25;const source=this.staticRoot.children.find(o=>o.userData?.kind==='terrain'&&o.userData.item?.id===item.id);if(source){source.updateWorldMatrix(true,true);const box=new THREE.Box3().setFromObject(source);if(Number.isFinite(box.min.y))y=box.min.y-.2}const grid=new THREE.GridHelper(span,divisions,0x7fc9e8,0x365f78);grid.position.set(pos.x,y,pos.z);for(const material of (Array.isArray(grid.material)?grid.material:[grid.material])){material.transparent=true;material.opacity=.24;material.depthWrite=false}grid.renderOrder=-10;grid.name=`${item.id}-tile-grid`;grid.userData={kind:'reference_grid',tile_size:TILE,span_world:span};this.referenceRoot.add(grid)}this.referenceRoot.visible=true}
  _terrainCoordinateFallback(item,origin,data){
    const span=finite(data?.static?.chunk_span_world)??512;
    const y=finite(this.player?.world?.y)??0;
    const cell=item.cell||{},parity=((Number(cell.x)||0)+(Number(cell.z)||0))&1;
    const group=new THREE.Group();group.name=`${item.id}-coordinate-fallback`;group.position.copy(this._display(item.world,origin));group.userData={kind:'terrain',item,asset_mode:'coordinate_fallback'};
    const face=new THREE.Mesh(new THREE.PlaneGeometry(span,span),new THREE.MeshLambertMaterial({color:parity?0x284867:0x213e59,transparent:true,opacity:.88,side:THREE.DoubleSide}));face.rotation.x=-Math.PI/2;face.position.y=y;group.add(face);
    const grid=new THREE.GridHelper(span,32,0x73b9e6,0x35566e);grid.position.y=y+.2;grid.material.transparent=true;grid.material.opacity=.58;group.add(grid);
    return group;
  }
  async _ensurePlayerVisual(){if(this.playerVisual)return;let meta=null;try{meta=await getJSON(`${API}/player/asset/meta?gender=${encodeURIComponent(this.gender)}`,3000)}catch{}this.playerMeta=meta;
    if(meta?.resource_kind==='nsbtx_billboard'){this.billboardStep=DIR_STEP[meta.registry?.sprite_controller_type]||0;const frame=(this.player?.orientation?.face_dir_raw??1)*this.billboardStep;try{const tex=await this._spriteTexture(frame);const s=new THREE.Sprite(new THREE.SpriteMaterial({map:tex,transparent:true,alphaTest:.1}));s.scale.set(32,32,1);s.center.set(.5,0);this.playerVisual=s;this.playerVisualMode='original_billboard';this.lastBillboardFrame=frame;this.playerAnchor.add(s);this.ui.onActorMode?.(this.playerVisualMode,meta);this.diag.player_mode=this.playerVisualMode;this._emitDiag();return}catch(e){this.diag.failed_assets.push({kind:'player_sprite',url:`${API}/player/asset/sprite/${frame}.png`,error:String(e.message||e)})}}
    this.playerVisual=this._pixelHero(0x4e8bd9);this.playerVisualMode='diagnostic_fallback';this.playerAnchor.add(this.playerVisual);this.diag.player_mode=this.playerVisualMode;this.ui.onActorMode?.(this.playerVisualMode,meta);this._emitDiag()}
  async _spriteTexture(frame){const k=`p:${this.gender}:${frame}`;if(this.spriteCache.has(k))return this.spriteCache.get(k);const p=new THREE.TextureLoader().loadAsync(`${API}/player/asset/sprite/${frame}.png?gender=${encodeURIComponent(this.gender)}`).then(t=>{t.colorSpace=THREE.SRGBColorSpace;t.magFilter=THREE.NearestFilter;t.minFilter=THREE.NearestFilter;return t});this.spriteCache.set(k,p);return p}
  async _updatePlayerFrame(p){if(this.playerVisualMode!=='original_billboard'||!this.playerVisual?.material)return;const step=this.billboardStep||0,face=p.orientation?.face_dir_raw??1,moving=p.locomotion?.phase==='Moving',anim=step>1&&moving?(Math.floor((p.frame||0)/5)%step):0,frame=face*step+anim;if(frame===this.lastBillboardFrame)return;try{this.playerVisual.material.map=await this._spriteTexture(frame);this.playerVisual.material.needsUpdate=true;this.lastBillboardFrame=frame}catch{}}
  _pixelHero(color){const g=new THREE.Group(),body=new THREE.Mesh(new THREE.BoxGeometry(9,14,6),new THREE.MeshLambertMaterial({color})),head=new THREE.Mesh(new THREE.BoxGeometry(9,9,8),new THREE.MeshLambertMaterial({color:0xe6c39c}));body.position.y=9;head.position.y=20;g.add(body,head);return g}
  applyPlayer(p){if(!p||p.status==='unresolved')return;const first=!this.player,zoneChanged=this.player&&p.zone_id!==this.player.zone_id;this.player=p;const d=this._display(p.world);this.playerTarget.copy(d);if(this.lastPlayerFrame==null||zoneChanged){this.playerDisplay.copy(d);this.playerAnchor.position.copy(d)}this.lastPlayerFrame=p.frame;const yaw=finite(p.orientation?.yaw_degrees_if_model_forward_is_south);if(yaw!=null&&this.playerVisualMode!=='original_billboard')this.playerAnchor.rotation.y=yaw*Math.PI/180;this._updatePlayerFrame(p);this.ui.onPlayer?.(p);if(first||zoneChanged)this.refreshScene(false).catch(e=>this.ui.onStatus?.('scene','degraded',e.message))}
  async _actorVisual(actor){const code=actor.obj_code_candidate??actor.model_id;const key=String(code);if(this.actorAssetCache.has(key))return this.actorAssetCache.get(key);const promise=(async()=>{try{const meta=await getJSON(`${LAB}/actors/${code}/asset`,2500);if(meta.resource_kind==='nsbtx_billboard'){const step=DIR_STEP[meta.registry?.sprite_controller_type]||0,frame=(actor.face_dir_raw??1)*step;const tex=await new THREE.TextureLoader().loadAsync(`${LAB}/actors/${code}/sprite/${frame}.png`);tex.colorSpace=THREE.SRGBColorSpace;tex.magFilter=THREE.NearestFilter;const s=new THREE.Sprite(new THREE.SpriteMaterial({map:tex,transparent:true,alphaTest:.1}));s.scale.set(30,46,1);s.center.set(.5,0);s.userData={asset_mode:'candidate_original_billboard',obj_code:code};return s}if(meta.resource_kind==='nsbmd_3d'){const g=await new Promise((res,rej)=>this.loader.load(`${LAB}/actors/${code}/model.glb`,x=>res(x.scene),undefined,rej));g.userData={asset_mode:'candidate_original_glb',obj_code:code};return g}}catch{}const f=this._pixelHero(0x6db3e6);f.userData={asset_mode:'fallback_marker',obj_code:code};return f})();this.actorAssetCache.set(key,promise);return promise}
  async applyActors(actors){if(!this.showActors)return;const seen=new Set(),same=actors.filter(a=>!a.is_player&&a.zone_id===this.player?.zone_id);this.diag.npc_total=same.length;this.diag.npc_original_count=0;this.diag.npc_fallback_count=0;for(const a of same){const id=String(a.slot??a.actor_uid);seen.add(id);let anchor=this.actorMarkers.get(id);if(!anchor){anchor=new THREE.Group();const visual=(await this._actorVisual(a)).clone(true);anchor.add(visual);anchor.userData={kind:'npc',actor:a,mode:visual.userData?.asset_mode||'fallback_marker'};this.actorMarkers.set(id,anchor);this.actorRoot.add(anchor)}anchor.position.copy(this._display(a.world));if(anchor.userData.mode?.startsWith('candidate_original'))this.diag.npc_original_count++;else this.diag.npc_fallback_count++}for(const [id,o] of this.actorMarkers)if(!seen.has(id)){this.actorRoot.remove(o);o.clear();this.actorMarkers.delete(id)}this._emitDiag();this.ui.onActors?.(same)}
  _clearActors(){for(const o of this.actorMarkers.values()){this.actorRoot.remove(o);o.clear()}this.actorMarkers.clear();this.diag.npc_total=0;this.diag.npc_original_count=0;this.diag.npc_fallback_count=0;this._emitDiag()}
  clearNavigationPath(){this.navigationPath=[];this.pathRoot.clear()}
  setNavigationPath(points){this.clearNavigationPath();this.navigationPath=Array.isArray(points)?points:[];if(this.navigationPath.length<2)return 0;const y=(finite(this.player?.world?.y)??0)+10,pts=this.navigationPath.map(p=>this._display({x:Number(p.x)*TILE+8,y,z:Number(p.z)*TILE+8})),mat=new THREE.LineBasicMaterial({color:0x43e0ff,depthTest:false}),geo=new THREE.BufferGeometry().setFromPoints(pts),line=new THREE.Line(geo,mat);this.pathRoot.add(line);return pts.length}

  _nodeForHit(hit){let node=hit?.object;while(node&&node!==this.worldRoot&&!node.userData?.kind)node=node.parent;return node&&node.userData?.kind?node:null}
  _sceneBounds(){const terrain=this.sceneData?.static?.terrains||[],span=Math.max(TILE,finite(this.sceneData?.static?.chunk_span_world)??512);if(!terrain.length)return null;const xs=terrain.map(x=>finite(x.world?.x)).filter(x=>x!=null),zs=terrain.map(x=>finite(x.world?.z)).filter(x=>x!=null);if(!xs.length||!zs.length)return null;return {minX:Math.min(...xs)-span/2,maxX:Math.max(...xs)+span/2,minZ:Math.min(...zs)-span/2,maxZ:Math.max(...zs)+span/2}}
  _pointerContext(event){
    const rect=this.renderer.domElement.getBoundingClientRect();if(!rect.width||!rect.height)return null;
    const cssX=event.clientX-rect.left,cssY=event.clientY-rect.top;
    this.pointer.x=(cssX/rect.width)*2-1;this.pointer.y=-(cssY/rect.height)*2+1;
    this.raycaster.setFromCamera(this.pointer,this.camera);
    const hits=this.raycaster.intersectObjects([this.playerAnchor,this.actorRoot,this.staticRoot],true),pickHit=hits.find(hit=>this._nodeForHit(hit)),pickNode=this._nodeForHit(pickHit),pointer={css:{x:cssX,y:cssY},device_px:{x:cssX*this.renderer.getPixelRatio(),y:cssY*this.renderer.getPixelRatio()},ndc:{x:this.pointer.x,y:this.pointer.y}};
    if(!this.player||this.player.status==='unresolved')return {hits,pickHit,pickNode,pointer,coordinate:null};
    const meshPoint=pickHit?.point?.clone?.();if(meshPoint&&pickHit.object?.isSkinnedMesh)meshPoint.applyMatrix4(pickHit.object.matrixWorld);
    // Empty canvas regions have no render mesh to intersect. Projecting onto
    // the player's elevation is useful only inside the loaded terrain bounds.
    const planePoint=new THREE.Vector3(),plane=new THREE.Plane(new THREE.Vector3(0,1,0),-this.playerDisplay.y),point=meshPoint||this.raycaster.ray.intersectPlane(plane,planePoint);
    if(!point)return {hits,pickHit,pickNode,pointer,coordinate:null};
    const worldX=point.x+this.origin.x,worldZ=point.z+this.origin.z;
    if(!meshPoint){const bounds=this._sceneBounds();if(bounds&&(worldX<bounds.minX||worldX>bounds.maxX||worldZ<bounds.minZ||worldZ>bounds.maxZ))return {hits,pickHit,pickNode,pointer,coordinate:{status:'outside_scene',confidence:'unresolved',source:'outside_scene_bounds',world:{x:worldX,y:point.y,z:worldZ},grid:null,tile_centre:null,chunk:null,scene_origin:{x:this.origin.x,z:this.origin.z},pointer,coordinate_contract:'GPos.x=floor(WPos.x/16); GPos.z=floor(WPos.z/16); stationary tile centre is WPos=(GPos*16)+8',note:'点击位置在场景半透明格网范围外，请在格网内点击。'}}}
    const gridX=Math.floor(worldX/TILE),gridZ=Math.floor(worldZ/TILE),liveSize=finite(this.player?.chunk?.tile_size),sceneSpan=finite(this.sceneData?.static?.chunk_span_world),chunkTileSize=liveSize&&liveSize>0?liveSize:(sceneSpan&&sceneSpan/TILE>0&&Number.isInteger(sceneSpan/TILE)?sceneSpan/TILE:null),mod=(value,size)=>((value%size)+size)%size;
    return {hits,pickHit,pickNode,pointer,coordinate:{
      status:'resolved',confidence:meshPoint?'candidate':'probable',source:meshPoint?'rendered_mesh_surface':'player_elevation_reference_plane',
      world:{x:worldX,y:point.y,z:worldZ},grid:{x:gridX,z:gridZ},tile_centre:{x:gridX*TILE+8,z:gridZ*TILE+8},
      chunk:chunkTileSize?{x:Math.floor(gridX/chunkTileSize),z:Math.floor(gridZ/chunkTileSize),tile_size:chunkTileSize,local_tile:{x:mod(gridX,chunkTileSize),z:mod(gridZ,chunkTileSize)}}:null,
      scene_origin:{x:this.origin.x,z:this.origin.z},pointer,
      coordinate_contract:'GPos.x=floor(WPos.x/16); GPos.z=floor(WPos.z/16); stationary tile centre is WPos=(GPos*16)+8',
      note:meshPoint?'X/Z comes from the same rendered mesh hit as the selected object; mesh Y is visual geometry only.':'No mesh was hit; X/Z is projected onto the player elevation reference plane.'
    }};
  }
  _hover(event){const result=this._pointerContext(event);if(result?.coordinate)this.ui.onPointer?.(result.coordinate,false)}
  _pick(event){
    const result=this._pointerContext(event);if(!result)return;const point=result.coordinate;
    if(point)this.ui.onPointer?.(point,true);
    const node=result.pickNode;if(node&&point?.status==='resolved'){this._highlight(node);const kind=node.userData.kind;const item=kind==='building'||kind==='terrain'?node.userData.item:kind==='npc'?node.userData.actor:this.player;const payload={...(item||{}),picked_coordinate:point};this.ui.onSelect?.({kind,id:node.name||node.userData.uid||node.userData.actor?.slot||'player',payload,node});return;}
    if(point?.status==='resolved'){this._highlight(null);this.ui.onSelect?.({kind:'map_point',id:`${point.grid.x},${point.grid.z}`,payload:point})}
  }
  _highlight(node){this.selectionRoot.clear();if(!node)return;try{const box=new THREE.BoxHelper(node,0x62d0ff);box.material.depthTest=false;box.renderOrder=999;this.selectionRoot.add(box)}catch{}}
  setLayerVisibility(kind,visible){for(const child of this.staticRoot.children){if(child.userData?.kind===kind)child.visible=!!visible}if(kind==='terrain')this.referenceRoot.visible=!!visible;if(kind==='npc')this.setRuntimeActors(visible);if(kind==='player')this.playerAnchor.visible=!!visible;}

  _frameCamera(env){const indoor=env==='interior',d=indoor?120:240,h=indoor?145:260;this.camera.position.set(this.playerDisplay.x+90,this.playerDisplay.y+h,this.playerDisplay.z+d);this.camera.lookAt(this.playerDisplay.x,this.playerDisplay.y+12,this.playerDisplay.z);this.controls.target.copy(this.playerDisplay)}
  _animate(now){if(this.disposed)return;requestAnimationFrame(t=>this._animate(t));this.playerDisplay.lerp(this.playerTarget,.3);this.playerAnchor.position.copy(this.playerDisplay);if(this.followPlayer){const indoor=this.sceneData?.environment==='interior',desired=new THREE.Vector3(this.playerDisplay.x+85,this.playerDisplay.y+(indoor?145:245),this.playerDisplay.z+(indoor?120:220));this.camera.position.lerp(desired,.08);this.camera.lookAt(this.playerDisplay.x,this.playerDisplay.y+12,this.playerDisplay.z)}else this.controls.update();if(now-this.lastRenderAt>=1000/TARGET_RENDER_FPS){this.renderer.render(this.scene,this.camera);this.lastRenderAt=now;this.fpsFrames++;if(now-this.fpsWindow>=1000){this.fps=Math.round(this.fpsFrames*1000/(now-this.fpsWindow));this.fpsFrames=0;this.fpsWindow=now;this.diag.fps=this.fps;this._emitDiag()}}}
  dispose(){this.disposed=true;this.loadingGeneration++;this.renderer.domElement.removeEventListener('click',this._onPick);this.renderer.domElement.removeEventListener('pointermove',this._onPointerMove);this._disposeRoot(this.referenceRoot);this.selectionRoot.clear();this.renderer.dispose();this.controls.dispose()}
}
