(function(){
  'use strict';
  const KEY='black2.workbench.locale';
  const DEFAULT='zh-CN';
  const dict={
    'zh-CN':{
      'app.title':'Pokémon Black 2 逆向工作台','app.subtitle':'IREJ · RAM/ROM 实证语义运行时','app.live':'实时','app.command':'命令','app.language':'语言','app.chinese':'中文','app.english':'English',
      'workspace.world':'世界','workspace.player':'主角','workspace.dialogue':'对话','workspace.memory':'内存','workspace.evidence':'证据','workspace.monitor':'监控','workspace.tools':'工具',
      'explorer.title':'资源浏览器','explorer.filter':'筛选对象…','explorer.currentScene':'当前场景','explorer.terrain':'地形','explorer.buildings':'建筑','explorer.actors':'运行时角色','explorer.warps':'出入口 / Warp','explorer.triggers':'触发器','explorer.player':'主角','explorer.empty':'暂无可显示对象',
      'inspector.title':'属性检查器','inspector.nothing':'选择场景中的主角、建筑、NPC 或资源以查看证据。','inspector.facts':'事实','inspector.confidence':'置信度','inspector.source':'来源','inspector.raw':'原始数据','inspector.actions':'操作','inspector.copy':'复制 JSON',
      'confidence.verified':'已验证','confidence.probable':'高可信','confidence.candidate':'候选','confidence.unresolved':'未解析','confidence.error':'错误',
      'world.follow':'跟随主角','world.frame':'定位主角','world.refresh':'重载场景','world.npc':'显示 NPC','world.grid':'证据网格','world.terrain':'地形','world.buildings':'建筑','world.scene':'场景','world.player':'主角','world.statusWaiting':'等待 PlayerRuntime…','world.sceneLoading':'正在加载原版 3D 世界…','world.selectHint':'点击查看坐标 · 滚轮不缩放 · 按住滚轮平移',
      'player.title':'主角运行时','player.discovery':'显式发现主角','player.discoveryNote':'只有点击时才允许一次受控 discovery；日常 UI 读取缓存。','player.position':'位置','player.orientation':'朝向','player.movement':'移动','player.mapper':'地图定位','player.asset':'角色资源','player.chain':'Root Chain','player.cached':'缓存样本',
      'dialogue.title':'对话运行时','dialogue.current':'当前对话','dialogue.visible':'可见文字','dialogue.loaded':'已加载文本流','dialogue.printer':'Printer 证据','dialogue.history':'对话时间线','dialogue.choices':'选项','dialogue.advance':'推进一次','dialogue.clear':'清空历史','dialogue.idle':'当前无活跃对话',
      'memory.title':'内存与结构','memory.description':'默认只查看已解析结构和 bounded tools；不会因为打开页面就扫描完整 4 MiB RAM。','memory.selection':'当前对象结构','memory.rawSnapshot':'RuntimeHub 原始缓存','memory.tools':'受控逆向工具','memory.openTracer':'打开 Memory Tracer','memory.openCheckpoints':'对话 Checkpoint','memory.heavy':'全量 RAM 取证','memory.heavyNote':'仅在需要新的未知结构证据时使用。',
      'evidence.title':'证据与校准','evidence.calibration':'空间校准','evidence.scenario':'场景类型','evidence.label':'标签','evidence.start':'开始录制','evidence.stop':'结束并导出','evidence.sample':'采样','evidence.reports':'报告','evidence.navigation':'观察式分层导航','evidence.download':'下载','evidence.noReports':'暂无报告',
      'monitor.title':'服务与性能','monitor.health':'运行健康','monitor.versions':'组件版本','monitor.logs':'生命周期日志','monitor.policy':'性能策略','monitor.refresh':'刷新','monitor.restart':'重启后端','monitor.http':'HTTP','monitor.bridge':'Bridge','monitor.semantic':'Semantic','monitor.frame':'帧','monitor.fps':'3D FPS','monitor.sceneLoad':'场景加载','monitor.failedAssets':'失败资源',
      'tools.title':'高级工具','tools.description':'这些工具可能执行写输入、受控内存读取或完整取证。Workbench 默认不会自动触发。','tool.controller':'输入控制器','tool.ramDumper':'Universal Evidence Dumper','tool.memoryTracer':'Memory Tracer','tool.dialogueCheckpoints':'Dialogue Checkpoints','tool.apiDocs':'API 文档',
      'dock.events':'事件','dock.assets':'资源错误','dock.navigation':'导航','dock.calibration':'校准','dock.performance':'性能','dock.memory':'原始/结构','dock.clear':'清空','dock.empty':'暂无记录',
      'status.http':'HTTP','status.bridge':'Bridge','status.player':'Player','status.scene':'Scene','status.rom':'ROM','status.online':'在线','status.waiting':'等待','status.offline':'离线',
      'action.open':'打开','action.refresh':'刷新','action.close':'关闭','action.cancel':'取消','action.save':'保存','action.export':'导出','action.copy':'复制','action.openLegacy':'打开高级工具',
      'nav.goalX':'目标 X','nav.goalY':'高度 Y（可空）','nav.goalZ':'目标 Z','nav.preview':'预览已验证路径','nav.clear':'清除路线','nav.observed':'Observed 3D Graph','nav.note':'只有真实走过的边才用于高可信路径；ROM permission 仍是候选。',
      'cal.outdoor_flat':'室外平地','cal.door_transition':'进门 / 出门','cal.indoor':'室内','cal.stairs':'楼梯 / 坡道','cal.bridge':'桥上 / 桥下','cal.npc':'NPC 附近','cal.building':'建筑校准','cal.general':'一般',
      'common.status':'状态','common.zone':'Zone','common.area':'Area','common.matrix':'Matrix','common.frame':'Frame','common.count':'数量','common.mode':'模式','common.address':'地址','common.position':'位置','common.rotation':'旋转','common.model':'模型','common.door':'DoorUID','common.source':'来源','common.reason':'原因','common.none':'无','common.loading':'加载中…','common.unavailable':'不可用','common.unknown':'未知'
    },
    'en':{
      'app.title':'Pokémon Black 2 Reverse Engineering Workbench','app.subtitle':'IREJ · evidence-grounded RAM/ROM semantic runtime','app.live':'LIVE','app.command':'Command','app.language':'Language','app.chinese':'中文','app.english':'English',
      'workspace.world':'World','workspace.player':'Player','workspace.dialogue':'Dialogue','workspace.memory':'Memory','workspace.evidence':'Evidence','workspace.monitor':'Monitor','workspace.tools':'Tools',
      'explorer.title':'Explorer','explorer.filter':'Filter objects…','explorer.currentScene':'Current Scene','explorer.terrain':'Terrain','explorer.buildings':'Buildings','explorer.actors':'Runtime Actors','explorer.warps':'Entrances / Warps','explorer.triggers':'Triggers','explorer.player':'Player','explorer.empty':'No objects to display',
      'inspector.title':'Inspector','inspector.nothing':'Select the player, a building, NPC or resource to inspect its evidence.','inspector.facts':'Facts','inspector.confidence':'Confidence','inspector.source':'Source','inspector.raw':'Raw Data','inspector.actions':'Actions','inspector.copy':'Copy JSON',
      'confidence.verified':'VERIFIED','confidence.probable':'PROBABLE','confidence.candidate':'CANDIDATE','confidence.unresolved':'UNRESOLVED','confidence.error':'ERROR',
      'world.follow':'Follow Player','world.frame':'Frame Player','world.refresh':'Reload Scene','world.npc':'Runtime NPCs','world.grid':'Evidence Grid','world.terrain':'Terrain','world.buildings':'Buildings','world.scene':'Scene','world.player':'Player','world.statusWaiting':'Waiting for PlayerRuntime…','world.sceneLoading':'Loading original 3D world…','world.selectHint':'Click for coordinates · wheel does not zoom · hold wheel to pan',
      'player.title':'Player Runtime','player.discovery':'Discover Player','player.discoveryNote':'A bounded discovery is allowed only when explicitly clicked; routine UI reads caches.','player.position':'Position','player.orientation':'Orientation','player.movement':'Movement','player.mapper':'Map Identity','player.asset':'Actor Asset','player.chain':'Root Chain','player.cached':'Cached Sample',
      'dialogue.title':'Dialogue Runtime','dialogue.current':'Current Dialogue','dialogue.visible':'Visible Text','dialogue.loaded':'Loaded Text Stream','dialogue.printer':'Printer Evidence','dialogue.history':'Dialogue Timeline','dialogue.choices':'Choices','dialogue.advance':'Advance Once','dialogue.clear':'Clear History','dialogue.idle':'No active dialogue',
      'memory.title':'Memory & Structures','memory.description':'Inspect decoded structures and bounded tools by default; opening this workspace never scans the full 4 MiB RAM.','memory.selection':'Selected Structure','memory.rawSnapshot':'RuntimeHub Raw Cache','memory.tools':'Bounded RE Tools','memory.openTracer':'Open Memory Tracer','memory.openCheckpoints':'Dialogue Checkpoints','memory.heavy':'Full RAM Evidence','memory.heavyNote':'Use only when new evidence for an unknown structure is required.',
      'evidence.title':'Evidence & Calibration','evidence.calibration':'Spatial Calibration','evidence.scenario':'Scenario','evidence.label':'Label','evidence.start':'Start Recording','evidence.stop':'Finish & Export','evidence.sample':'Sample','evidence.reports':'Reports','evidence.navigation':'Observed Layered Navigation','evidence.download':'Download','evidence.noReports':'No reports yet',
      'monitor.title':'Services & Performance','monitor.health':'Runtime Health','monitor.versions':'Component Versions','monitor.logs':'Lifecycle Log','monitor.policy':'Performance Policy','monitor.refresh':'Refresh','monitor.restart':'Restart Backend','monitor.http':'HTTP','monitor.bridge':'Bridge','monitor.semantic':'Semantic','monitor.frame':'Frame','monitor.fps':'3D FPS','monitor.sceneLoad':'Scene Load','monitor.failedAssets':'Failed Assets',
      'tools.title':'Advanced Tools','tools.description':'These tools may write controller input, perform bounded RAM reads, or capture full evidence. The Workbench never triggers them automatically.','tool.controller':'Input Controller','tool.ramDumper':'Universal Evidence Dumper','tool.memoryTracer':'Memory Tracer','tool.dialogueCheckpoints':'Dialogue Checkpoints','tool.apiDocs':'API Docs',
      'dock.events':'Events','dock.assets':'Asset Errors','dock.navigation':'Navigation','dock.calibration':'Calibration','dock.performance':'Performance','dock.memory':'Raw / Structure','dock.clear':'Clear','dock.empty':'No records',
      'status.http':'HTTP','status.bridge':'Bridge','status.player':'Player','status.scene':'Scene','status.rom':'ROM','status.online':'Online','status.waiting':'Waiting','status.offline':'Offline',
      'action.open':'Open','action.refresh':'Refresh','action.close':'Close','action.cancel':'Cancel','action.save':'Save','action.export':'Export','action.copy':'Copy','action.openLegacy':'Open Advanced Tool',
      'nav.goalX':'Goal X','nav.goalY':'Elevation Y (optional)','nav.goalZ':'Goal Z','nav.preview':'Preview Verified Path','nav.clear':'Clear Path','nav.observed':'Observed 3D Graph','nav.note':'Only successfully observed movement edges drive high-confidence paths; ROM permission remains candidate evidence.',
      'cal.outdoor_flat':'Outdoor Flat','cal.door_transition':'Door Transition','cal.indoor':'Indoor','cal.stairs':'Stairs / Slope','cal.bridge':'Bridge / Underpass','cal.npc':'Near NPC','cal.building':'Building Calibration','cal.general':'General',
      'common.status':'Status','common.zone':'Zone','common.area':'Area','common.matrix':'Matrix','common.frame':'Frame','common.count':'Count','common.mode':'Mode','common.address':'Address','common.position':'Position','common.rotation':'Rotation','common.model':'Model','common.door':'DoorUID','common.source':'Source','common.reason':'Reason','common.none':'None','common.loading':'Loading…','common.unavailable':'Unavailable','common.unknown':'Unknown'
    }
  };
  let locale=localStorage.getItem(KEY)||DEFAULT;
  if(!dict[locale])locale=DEFAULT;
  const listeners=new Set();
  function t(key,fallback){return dict[locale]?.[key]??dict[DEFAULT]?.[key]??fallback??key;}
  function apply(root=document){root.documentElement && (root.documentElement.lang=locale);root.querySelectorAll?.('[data-i18n]').forEach(el=>{el.textContent=t(el.dataset.i18n,el.textContent)});root.querySelectorAll?.('[data-i18n-placeholder]').forEach(el=>{el.setAttribute('placeholder',t(el.dataset.i18nPlaceholder,el.getAttribute('placeholder')||''))});}
  function setLocale(next){if(!dict[next])return false;locale=next;localStorage.setItem(KEY,locale);apply(document);listeners.forEach(fn=>fn(locale));return true;}
  function getLocale(){return locale;}
  function subscribe(fn){listeners.add(fn);return()=>listeners.delete(fn);}
  window.Black2I18n={t,apply,setLocale,getLocale,subscribe,supported:Object.keys(dict),defaultLocale:DEFAULT};
})();
