(function(){
  'use strict';
  const KEY='black2.workbench.locale';
  const DEFAULT='zh-CN';
  const dict={
    'zh-CN':{
      'app.title':'Pokémon Black 2 逆向工作台','app.subtitle':'IREJ · RAM/ROM 实证语义运行时','app.live':'实时','app.command':'命令','app.language':'语言','app.chinese':'中文','app.english':'English',
      'workspace.world':'世界','workspace.player':'主角','workspace.dialogue':'对话','workspace.battle':'战斗 / 图鉴','workspace.memory':'内存','workspace.evidence':'证据','workspace.monitor':'监控','workspace.tools':'工具',
      'explorer.title':'资源浏览器','explorer.filter':'筛选对象…','explorer.currentScene':'当前场景','explorer.terrain':'地形','explorer.buildings':'建筑','explorer.actors':'运行时角色','explorer.warps':'出入口 / Warp','explorer.triggers':'触发器','explorer.player':'主角','explorer.empty':'暂无可显示对象',
      'inspector.title':'属性检查器','inspector.nothing':'选择场景中的主角、建筑、NPC 或资源以查看证据。','inspector.facts':'事实','inspector.confidence':'置信度','inspector.source':'来源','inspector.raw':'原始数据','inspector.actions':'操作','inspector.copy':'复制 JSON',
      'confidence.verified':'已验证','confidence.probable':'高可信','confidence.candidate':'候选','confidence.unresolved':'未解析','confidence.error':'错误',
      'world.follow':'跟随主角','world.frame':'定位主角','world.refresh':'重载场景','world.staticZone':'静态 Zone','world.staticPreview':'预览','world.liveScene':'返回实时','world.liveMode':'实时','world.staticMode':'静态预览','world.npc':'显示 NPC','world.grid':'证据网格','world.terrain':'地形','world.buildings':'建筑','world.scene':'场景','world.player':'主角','world.statusWaiting':'等待 PlayerRuntime…','world.sceneLoading':'正在加载原版 3D 世界…','world.selectHint':'点击查看坐标 · 滚轮缩放 · 按住滚轮平移',
      'player.title':'主角运行时','player.discovery':'显式发现主角','player.discoveryNote':'只有点击时才允许一次受控 discovery；日常 UI 读取缓存。','player.position':'位置','player.orientation':'朝向','player.movement':'移动','player.mapper':'地图定位','player.asset':'角色资源','player.chain':'Root Chain','player.cached':'缓存样本',
      'dialogue.title':'对话运行时','dialogue.current':'当前对话','dialogue.visible':'可见文字','dialogue.loaded':'已加载文本流','dialogue.printer':'Printer 证据','dialogue.history':'对话时间线','dialogue.choices':'选项','dialogue.advance':'推进一次','dialogue.clear':'清空历史','dialogue.idle':'当前无活跃对话',
      'battle.title':'战斗与图鉴','battle.refresh':'刷新战斗状态','battle.decoder':'战斗解码器','battle.active':'战斗状态','battle.actions':'战斗动作','battle.actionType':'动作类型','battle.moveSlot':'招式槽位','battle.partySlot':'队伍槽位','battle.itemId':'道具 ID','battle.target':'目标','battle.submit':'提交动作','battle.locked':'战斗状态未解析，动作已锁定','battle.evidence':'所需证据','battle.dex':'黑 2 / 白 2 资料库','battle.search':'搜索编号、英文或中文名','battle.entity':'资料类型','battle.pokemon':'宝可梦','battle.moves':'招式','battle.items':'道具','battle.abilities':'特性','battle.searchButton':'查询','battle.results':'查询结果','battle.detail':'详细资料','battle.noResults':'没有匹配结果','battle.selectHint':'选择一条资料查看完整字段','battle.loading':'正在读取资料…','battle.source':'离线资料来源','battle.summary':'资料规模','battle.status':'当前状态','battle.unresolved':'未解析','battle.useMove':'使用招式','battle.switch':'切换宝可梦','battle.useItem':'使用道具','battle.run':'逃跑','battle.none':'无',
      'memory.title':'内存与结构','memory.description':'默认只查看已解析结构和 bounded tools；不会因为打开页面就扫描完整 4 MiB RAM。','memory.selection':'当前对象结构','memory.rawSnapshot':'RuntimeHub 原始缓存','memory.tools':'受控逆向工具','memory.openTracer':'打开 Memory Tracer','memory.openCheckpoints':'对话 Checkpoint','memory.heavy':'全量 RAM 取证','memory.heavyNote':'仅在需要新的未知结构证据时使用。',
      'evidence.title':'证据与校准','evidence.calibration':'空间校准','evidence.scenario':'场景类型','evidence.label':'标签','evidence.start':'开始录制','evidence.stop':'结束并导出','evidence.sample':'采样','evidence.reports':'报告','evidence.navigation':'观察式分层导航','evidence.download':'下载','evidence.noReports':'暂无报告',
      'monitor.title':'服务与性能','monitor.health':'运行健康','monitor.versions':'组件版本','monitor.logs':'生命周期日志','monitor.policy':'性能策略','monitor.refresh':'刷新','monitor.restart':'重启后端','monitor.http':'HTTP','monitor.bridge':'Bridge','monitor.semantic':'Semantic','monitor.frame':'帧','monitor.fps':'3D FPS','monitor.sceneLoad':'场景加载','monitor.failedAssets':'失败资源','monitor.popup':'BizHawk 弹窗',
      'tools.title':'高级工具','tools.description':'这些工具可能执行写输入、受控内存读取或完整取证。Workbench 默认不会自动触发。','tool.controller':'输入控制器','tool.ramDumper':'Universal Evidence Dumper','tool.memoryTracer':'Memory Tracer','tool.dialogueCheckpoints':'Dialogue Checkpoints','tool.apiDocs':'API 文档',
      'dock.events':'事件','dock.assets':'资源错误','dock.navigation':'导航','dock.calibration':'校准','dock.performance':'性能','dock.memory':'原始/结构','dock.clear':'清空','dock.empty':'暂无记录',
      'status.http':'HTTP','status.bridge':'Bridge','status.player':'Player','status.scene':'Scene','status.rom':'ROM','status.online':'在线','status.waiting':'等待','status.offline':'离线',
      'action.open':'打开','action.refresh':'刷新','action.close':'关闭','action.cancel':'取消','action.save':'保存','action.export':'导出','action.copy':'复制','action.openLegacy':'打开高级工具',
      'nav.goalZone':'地图 Zone','nav.goalX':'目标 X','nav.goalY':'高度层 Y','nav.goalZ':'目标 Z','nav.preview':'规划路线','nav.start':'开始寻路','nav.cancel':'取消寻路','nav.clear':'清除路线','nav.observed':'Observed 3D Graph','nav.note':'目的地使用 Zone + GPos (X/Y/Z)；路线由服务端根据碰撞、层高与地图连接规划。','nav.trigger':'目的地','nav.pickOnMap':'点击寻路','nav.pickWaiting':'请点击地图…','nav.pickHint':'点击地图上的可见位置选择目的地','nav.chooseKnown':'选择已知坐标…','nav.currentPosition':'主角当前位置','nav.previewAnchor':'静态画面锚点','nav.observedStart':'已观测路线起点','nav.observedNode':'已观测节点','nav.lastPicked':'上次地图选点','nav.runtimeActor':'运行时角色','nav.playerLayerUnavailable':'当前主角的 Zone 或高度层不可用','nav.invalidCoordinate':'请输入完整的整数 Zone / X / Y / Z','nav.staticStartUnavailable':'静态预览缺少可用的候选起点','nav.requesting':'正在计算路线…','nav.planning':'规划中…','nav.ready':'路线已就绪','nav.blocked':'路线被阻塞','nav.goalChanged':'目标已修改，请重新规划','nav.nodes':'节点','nav.steps':'步','nav.sceneChanged':'地图状态已经变化，请重新规划','nav.executionAvailable':'可执行','nav.executionUnavailable':'仅预览','nav.starting':'正在创建寻路任务…','nav.cancelling':'正在取消寻路任务…','nav.taskTitle':'寻路任务','nav.status.idle':'等待目标','nav.status.selected':'已选目标','nav.status.planning':'规划中','nav.status.ready':'可到达','nav.status.partial':'部分路线','nav.status.blocked':'不可到达','nav.status.stale':'已过期','nav.status.queued':'排队中','nav.status.prechecking':'执行前检查','nav.status.executing':'行走中','nav.status.cancelling':'取消中','nav.status.succeeded':'已到达','nav.status.failed':'已停止','nav.status.cancelled':'已取消','nav.status.error':'规划失败','nav.task.queued':'任务排队','nav.task.prechecking':'执行前检查','nav.task.executing':'正在行走','nav.task.cancelling':'取消中','nav.task.succeeded':'已到达','nav.task.failed':'执行失败','nav.task.cancelled':'已取消','nav.segment.local':'地图内路线','nav.segment.connector':'地图切换',
      'cal.outdoor_flat':'室外平地','cal.door_transition':'进门 / 出门','cal.indoor':'室内','cal.stairs':'楼梯 / 坡道','cal.bridge':'桥上 / 桥下','cal.npc':'NPC 附近','cal.building':'建筑校准','cal.general':'一般',
      'common.status':'状态','common.zone':'Zone','common.area':'Area','common.matrix':'Matrix','common.frame':'Frame','common.count':'数量','common.mode':'模式','common.address':'地址','common.position':'位置','common.rotation':'旋转','common.model':'模型','common.door':'DoorUID','common.source':'来源','common.reason':'原因','common.none':'无','common.loading':'加载中…','common.unavailable':'不可用','common.unknown':'未知'
    },
    'en':{
      'app.title':'Pokémon Black 2 Reverse Engineering Workbench','app.subtitle':'IREJ · evidence-grounded RAM/ROM semantic runtime','app.live':'LIVE','app.command':'Command','app.language':'Language','app.chinese':'中文','app.english':'English',
      'workspace.world':'World','workspace.player':'Player','workspace.dialogue':'Dialogue','workspace.battle':'Battle / Dex','workspace.memory':'Memory','workspace.evidence':'Evidence','workspace.monitor':'Monitor','workspace.tools':'Tools',
      'explorer.title':'Explorer','explorer.filter':'Filter objects…','explorer.currentScene':'Current Scene','explorer.terrain':'Terrain','explorer.buildings':'Buildings','explorer.actors':'Runtime Actors','explorer.warps':'Entrances / Warps','explorer.triggers':'Triggers','explorer.player':'Player','explorer.empty':'No objects to display',
      'inspector.title':'Inspector','inspector.nothing':'Select the player, a building, NPC or resource to inspect its evidence.','inspector.facts':'Facts','inspector.confidence':'Confidence','inspector.source':'Source','inspector.raw':'Raw Data','inspector.actions':'Actions','inspector.copy':'Copy JSON',
      'confidence.verified':'VERIFIED','confidence.probable':'PROBABLE','confidence.candidate':'CANDIDATE','confidence.unresolved':'UNRESOLVED','confidence.error':'ERROR',
      'world.follow':'Follow Player','world.frame':'Frame Player','world.refresh':'Reload Scene','world.staticZone':'Static Zone','world.staticPreview':'Preview','world.liveScene':'Back to live','world.liveMode':'LIVE','world.staticMode':'STATIC PREVIEW','world.npc':'Runtime NPCs','world.grid':'Evidence Grid','world.terrain':'Terrain','world.buildings':'Buildings','world.scene':'Scene','world.player':'Player','world.statusWaiting':'Waiting for PlayerRuntime…','world.sceneLoading':'Loading original 3D world…','world.selectHint':'Click for coordinates · wheel zooms · hold wheel to pan',
      'player.title':'Player Runtime','player.discovery':'Discover Player','player.discoveryNote':'A bounded discovery is allowed only when explicitly clicked; routine UI reads caches.','player.position':'Position','player.orientation':'Orientation','player.movement':'Movement','player.mapper':'Map Identity','player.asset':'Actor Asset','player.chain':'Root Chain','player.cached':'Cached Sample',
      'dialogue.title':'Dialogue Runtime','dialogue.current':'Current Dialogue','dialogue.visible':'Visible Text','dialogue.loaded':'Loaded Text Stream','dialogue.printer':'Printer Evidence','dialogue.history':'Dialogue Timeline','dialogue.choices':'Choices','dialogue.advance':'Advance Once','dialogue.clear':'Clear History','dialogue.idle':'No active dialogue',
      'battle.title':'Battle & Dex','battle.refresh':'Refresh Battle State','battle.decoder':'Battle Decoder','battle.active':'Battle State','battle.actions':'Battle Actions','battle.actionType':'Action type','battle.moveSlot':'Move slot','battle.partySlot':'Party slot','battle.itemId':'Item ID','battle.target':'Target','battle.submit':'Submit Action','battle.locked':'Battle state is unresolved; actions are locked','battle.evidence':'Evidence required','battle.dex':'Black 2 / White 2 reference data','battle.search':'Search number, English or Chinese name','battle.entity':'Entity type','battle.pokemon':'Pokemon','battle.moves':'Moves','battle.items':'Items','battle.abilities':'Abilities','battle.searchButton':'Search','battle.results':'Results','battle.detail':'Details','battle.noResults':'No matching entries','battle.selectHint':'Select an entry to inspect all fields','battle.loading':'Loading reference data…','battle.source':'Offline data source','battle.summary':'Dataset size','battle.status':'Current status','battle.unresolved':'Unresolved','battle.useMove':'Use move','battle.switch':'Switch Pokemon','battle.useItem':'Use item','battle.run':'Run','battle.none':'None',
      'memory.title':'Memory & Structures','memory.description':'Inspect decoded structures and bounded tools by default; opening this workspace never scans the full 4 MiB RAM.','memory.selection':'Selected Structure','memory.rawSnapshot':'RuntimeHub Raw Cache','memory.tools':'Bounded RE Tools','memory.openTracer':'Open Memory Tracer','memory.openCheckpoints':'Dialogue Checkpoints','memory.heavy':'Full RAM Evidence','memory.heavyNote':'Use only when new evidence for an unknown structure is required.',
      'evidence.title':'Evidence & Calibration','evidence.calibration':'Spatial Calibration','evidence.scenario':'Scenario','evidence.label':'Label','evidence.start':'Start Recording','evidence.stop':'Finish & Export','evidence.sample':'Sample','evidence.reports':'Reports','evidence.navigation':'Observed Layered Navigation','evidence.download':'Download','evidence.noReports':'No reports yet',
      'monitor.title':'Services & Performance','monitor.health':'Runtime Health','monitor.versions':'Component Versions','monitor.logs':'Lifecycle Log','monitor.policy':'Performance Policy','monitor.refresh':'Refresh','monitor.restart':'Restart Backend','monitor.http':'HTTP','monitor.bridge':'Bridge','monitor.semantic':'Semantic','monitor.frame':'Frame','monitor.fps':'3D FPS','monitor.sceneLoad':'Scene Load','monitor.failedAssets':'Failed Assets','monitor.popup':'BizHawk popup',
      'tools.title':'Advanced Tools','tools.description':'These tools may write controller input, perform bounded RAM reads, or capture full evidence. The Workbench never triggers them automatically.','tool.controller':'Input Controller','tool.ramDumper':'Universal Evidence Dumper','tool.memoryTracer':'Memory Tracer','tool.dialogueCheckpoints':'Dialogue Checkpoints','tool.apiDocs':'API Docs',
      'dock.events':'Events','dock.assets':'Asset Errors','dock.navigation':'Navigation','dock.calibration':'Calibration','dock.performance':'Performance','dock.memory':'Raw / Structure','dock.clear':'Clear','dock.empty':'No records',
      'status.http':'HTTP','status.bridge':'Bridge','status.player':'Player','status.scene':'Scene','status.rom':'ROM','status.online':'Online','status.waiting':'Waiting','status.offline':'Offline',
      'action.open':'Open','action.refresh':'Refresh','action.close':'Close','action.cancel':'Cancel','action.save':'Save','action.export':'Export','action.copy':'Copy','action.openLegacy':'Open Advanced Tool',
      'nav.goalZone':'Map Zone','nav.goalX':'Goal X','nav.goalY':'Layer Y','nav.goalZ':'Goal Z','nav.preview':'Plan Route','nav.start':'Start Navigation','nav.cancel':'Cancel Navigation','nav.clear':'Clear Route','nav.observed':'Observed 3D Graph','nav.note':'Destinations use Zone + GPos (X/Y/Z); the server plans with collision, elevation and map connectors.','nav.trigger':'Destination','nav.pickOnMap':'Pick on Map','nav.pickWaiting':'Click the map…','nav.pickHint':'Click a visible map position to choose the destination','nav.chooseKnown':'Choose known coordinates…','nav.currentPosition':'Current player position','nav.previewAnchor':'Static scene anchor','nav.observedStart':'Observed route start','nav.observedNode':'Observed node','nav.lastPicked':'Last map pick','nav.runtimeActor':'Runtime actor','nav.playerLayerUnavailable':'The current player Zone or elevation layer is unavailable','nav.invalidCoordinate':'Enter integer Zone / X / Y / Z values','nav.staticStartUnavailable':'Static preview has no usable candidate start','nav.requesting':'Calculating route…','nav.planning':'Planning…','nav.ready':'Route ready','nav.blocked':'Route blocked','nav.goalChanged':'The target changed; plan the route again','nav.nodes':'nodes','nav.steps':'steps','nav.sceneChanged':'The map state changed; plan the route again','nav.executionAvailable':'Execution available','nav.executionUnavailable':'Preview only','nav.starting':'Creating navigation task…','nav.cancelling':'Cancelling navigation task…','nav.taskTitle':'Navigation task','nav.status.idle':'Waiting for target','nav.status.selected':'Target selected','nav.status.planning':'Planning','nav.status.ready':'Reachable','nav.status.partial':'Partial route','nav.status.blocked':'Unreachable','nav.status.stale':'Stale','nav.status.queued':'Queued','nav.status.prechecking':'Prechecking','nav.status.executing':'Walking','nav.status.cancelling':'Cancelling','nav.status.succeeded':'Arrived','nav.status.failed':'Stopped','nav.status.cancelled':'Cancelled','nav.status.error':'Planning failed','nav.task.queued':'Task queued','nav.task.prechecking':'Prechecking','nav.task.executing':'Walking','nav.task.cancelling':'Cancelling','nav.task.succeeded':'Arrived','nav.task.failed':'Execution failed','nav.task.cancelled':'Cancelled','nav.segment.local':'Local route','nav.segment.connector':'Map transition',
      'cal.outdoor_flat':'Outdoor Flat','cal.door_transition':'Door Transition','cal.indoor':'Indoor','cal.stairs':'Stairs / Slope','cal.bridge':'Bridge / Underpass','cal.npc':'Near NPC','cal.building':'Building Calibration','cal.general':'General',
      'common.status':'Status','common.zone':'Zone','common.area':'Area','common.matrix':'Matrix','common.frame':'Frame','common.count':'Count','common.mode':'Mode','common.address':'Address','common.position':'Position','common.rotation':'Rotation','common.model':'Model','common.door':'DoorUID','common.source':'Source','common.reason':'Reason','common.none':'None','common.loading':'Loading…','common.unavailable':'Unavailable','common.unknown':'Unknown'
    }
  };
  Object.assign(dict['zh-CN'],{'nav.movement':'移动方式','nav.mode.auto':'自动（安全）','nav.mode.walk':'走路','nav.mode.run':'跑步（按住 B）','nav.mode.bike':'自行车','nav.mode.surf':'冲浪','nav.movementChanged':'移动方式已修改，请重新规划','nav.intent.route':'普通路线','nav.intent.walk_to_tile':'固定坐标（只走到该格）','nav.intent.interact':'走到 NPC 旁并互动','nav.intentChanged':'导航语义已修改，请重新规划'});
  Object.assign(dict.en,{'nav.movement':'Movement mode','nav.mode.auto':'Auto (safe)','nav.mode.walk':'Walk','nav.mode.run':'Run (hold B)','nav.mode.bike':'Bicycle','nav.mode.surf':'Surf','nav.movementChanged':'Movement mode changed; plan the route again','nav.intent.route':'Normal route','nav.intent.walk_to_tile':'Fixed tile (walk exactly here)','nav.intent.interact':'Walk to NPC and interact','nav.intentChanged':'Navigation intent changed; plan the route again'});
  let locale=localStorage.getItem(KEY)||DEFAULT;
  if(!dict[locale])locale=DEFAULT;
  const listeners=new Set();
  function t(key,fallback){return dict[locale]?.[key]??dict[DEFAULT]?.[key]??fallback??key;}
  function apply(root=document){root.documentElement && (root.documentElement.lang=locale);root.querySelectorAll?.('[data-i18n]').forEach(el=>{el.textContent=t(el.dataset.i18n,el.textContent)});root.querySelectorAll?.('[data-i18n-placeholder]').forEach(el=>{el.setAttribute('placeholder',t(el.dataset.i18nPlaceholder,el.getAttribute('placeholder')||''))});}
  function setLocale(next){if(!dict[next])return false;locale=next;localStorage.setItem(KEY,locale);apply(document);listeners.forEach(fn=>fn(locale));return true;}
  function getLocale(){return locale;}
  function subscribe(fn){listeners.add(fn);return()=>listeners.delete(fn);}
  window.Black2I18n={t,apply,setLocale,getLocale,subscribe,supported:Object.keys(dict),defaultLocale:DEFAULT};
})();
